import "server-only";

import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/auth";
import { supabaseAdmin } from "@/lib/supabase/admin";
import { ConsultingHttpError } from "@/lib/consulting/workflow";

export { supabaseAdmin };
const admins = ["ADMIN", "CO_ADMIN"];
export async function requireDeliveryAdmin() { const session = await getServerSession(authOptions); if (!session?.user?.id) throw new ConsultingHttpError(401, "Authentication required."); if (!admins.includes(session.user.role)) throw new ConsultingHttpError(403, "Project delivery permission is required."); return { userId: session.user.id }; }
export async function requireDeliveryClient() { const session = await getServerSession(authOptions); if (!session?.user?.id || session.user.role !== "CLIENT") throw new ConsultingHttpError(403, "A client account is required."); const { data } = await supabaseAdmin.from("client_profiles").select("id").eq("user_id", session.user.id).maybeSingle(); if (!data) throw new ConsultingHttpError(403, "Client account is not linked."); return { userId: session.user.id, clientId: data.id }; }
export function deliveryError(error: unknown) { return Response.json({ error: error instanceof Error ? error.message : "Project delivery request failed." }, { status: error instanceof ConsultingHttpError ? error.status : 500 }); }
async function activity(projectId: string, entityType: string, entityId: string | null, actorId: string, eventType: string, metadata: Record<string, unknown> = {}) { const { error } = await supabaseAdmin.from("project_delivery_activity").insert({ project_id: projectId, entity_type: entityType, entity_id: entityId, actor_id: actorId, event_type: eventType, metadata }); if (error) throw new Error(error.message); }

export async function activateWorkspace(projectId: string, userId: string) {
  const { data: project } = await supabaseAdmin.from("consulting_projects").select("*").eq("id", projectId).maybeSingle();
  if (!project) throw new ConsultingHttpError(404, "Project not found.");
  if (project.status !== "active") throw new ConsultingHttpError(409, "Project must be active after verified payment and kickoff.");
  const { data: existing } = await supabaseAdmin.from("project_workspaces").select("*").eq("project_id", projectId).maybeSingle(); if (existing) return existing;
  const { data: workspace, error } = await supabaseAdmin.from("project_workspaces").insert({ project_id: project.id, client_id: project.client_id, company_id: project.company_id, scope_id: project.scope_id, agreement_id: project.agreement_id, status: "planning", created_by: userId, summary: { projectNumber: project.project_number } }).select("*").single(); if (error) throw new Error(error.message);
  await activity(workspace.id, "workspace", workspace.id, userId, "workspace_activated", { projectNumber: project.project_number }); return workspace;
}

export async function createMilestone(projectId: string, userId: string, input: Record<string, unknown>) { const { data: workspace } = await supabaseAdmin.from("project_workspaces").select("id,status").eq("id", projectId).maybeSingle(); if (!workspace || !["planning", "active"].includes(workspace.status)) throw new ConsultingHttpError(409, "Workspace is not ready for milestones."); if (!input.name) throw new ConsultingHttpError(400, "Milestone name is required."); const { data, error } = await supabaseAdmin.from("project_milestones").insert({ project_id: projectId, name: input.name, objective: input.objective || null, description: input.description || null, planned_start: input.plannedStart || null, planned_completion: input.plannedCompletion || null, owner_id: input.ownerId || null, exit_criteria: input.exitCriteria || [], created_by: userId }).select("*").single(); if (error) throw new Error(error.message); await activity(projectId, "milestone", data.id, userId, "milestone_created", { milestoneNumber: data.milestone_number }); return data; }
export async function createTask(projectId: string, userId: string, input: Record<string, unknown>) { if (!input.title) throw new ConsultingHttpError(400, "Task title is required."); const { data, error } = await supabaseAdmin.from("project_tasks").insert({ project_id: projectId, milestone_id: input.milestoneId || null, title: input.title, description: input.description || null, owner_id: input.ownerId || null, priority: input.priority || "medium", due_date: input.dueDate || null, client_visible: input.clientVisible === true, created_by: userId }).select("*").single(); if (error) throw new Error(error.message); await activity(projectId, "task", data.id, userId, "task_created", { taskNumber: data.task_number }); return data; }
export async function createChangeRequest(projectId: string, userId: string, clientId: string, input: Record<string, unknown>) { if (!input.title || !input.description) throw new ConsultingHttpError(400, "Change title and description are required."); const { data, error } = await supabaseAdmin.from("change_requests").insert({ project_id: projectId, client_id: clientId, requested_by: userId, title: input.title, description: input.description, status: "submitted", impact: input.impact || {} }).select("*").single(); if (error) throw new Error(error.message); await activity(projectId, "change_request", data.id, userId, "change_request_submitted", { changeNumber: data.change_number }); return data; }
export async function createTicket(projectId: string, userId: string, clientId: string, input: Record<string, unknown>) { if (!input.title || !input.description) throw new ConsultingHttpError(400, "Ticket title and description are required."); const { data, error } = await supabaseAdmin.from("support_tickets").insert({ project_id: projectId, client_id: clientId, requester_id: userId, title: input.title, description: input.description, type: input.type || "question", severity: input.severity || "medium", business_impact: input.businessImpact || null }).select("id,ticket_number,title,status,severity,created_at").single(); if (error) throw new Error(error.message); await activity(projectId, "support_ticket", data.id, userId, "support_ticket_created", { ticketNumber: data.ticket_number }); return data; }
