"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { useRouter } from "next/navigation";
import { DocumentActionBar } from "@/components/document/DocumentActionBar";
import { DocumentFooter } from "@/components/document/DocumentFooter";
import { DocumentHeader } from "@/components/document/DocumentHeader";
import { DocumentContainer, DocumentShell } from "@/components/document/DocumentShell";
import { validateQuestion, validateSection } from "@/lib/assessments/validation";
import type { AssessmentAnswerValue, AssessmentFile, AssessmentQuestion, ClientAssessment } from "@/types/assessment";

const queryKey=["client","assessment"] as const;
async function jsonRequest<T>(url:string,init:RequestInit):Promise<T>{const response=await fetch(url,{...init,headers:{"Content-Type":"application/json",...init.headers}});const body=await response.json();if(!response.ok)throw new Error(body.error||"Request failed.");return body;}

export function AssessmentRenderer({assessment}:{assessment:ClientAssessment}){
  const router=useRouter(); const queryClient=useQueryClient(); const [sectionIndex,setSectionIndex]=useState(Math.max(0,assessment.currentSection-1)); const [answers,setAnswers]=useState<Record<string,AssessmentAnswerValue>>(assessment.answers); const [errors,setErrors]=useState<Record<string,string>>({}); const [message,setMessage]=useState(""); const [dirty,setDirty]=useState(false); const autosaveRef=useRef<ReturnType<typeof setTimeout>|null>(null);
  const section=assessment.template.sections[sectionIndex]; const progress=Math.round(((sectionIndex+1)/assessment.template.sections.length)*100);
  const draftMutation=useMutation({mutationFn:(payload:{answers:Record<string,AssessmentAnswerValue>;currentSection:number})=>jsonRequest<{savedAt:string}>("/api/client/assessment/draft",{method:"PATCH",body:JSON.stringify(payload)}),onSuccess:(result)=>{setDirty(false);setMessage(`Saved ${new Date(result.savedAt).toLocaleString()}`);queryClient.invalidateQueries({queryKey});},onError:(error)=>setMessage(`Not saved: ${error.message}`)});
  const completeMutation=useMutation({mutationFn:()=>jsonRequest<{ok:boolean;errors:{questionKey:string;message:string}[]}>("/api/client/assessment/section/complete",{method:"POST",body:JSON.stringify({sectionKey:section.key,answers})})});
  const submitMutation=useMutation({mutationFn:()=>jsonRequest<{ok:boolean;errors:{questionKey:string;message:string}[]}>("/api/client/assessment/submit",{method:"POST",body:JSON.stringify({answers})})});
  const fileMutation=useMutation({mutationFn:async({questionKey,file}:{questionKey:string;file:File})=>{const form=new FormData();form.set("questionKey",questionKey);form.set("file",file);const response=await fetch("/api/client/assessment/files",{method:"POST",body:form});const body=await response.json();if(!response.ok)throw new Error(body.error||"Upload failed.");return body;},onSuccess:()=>queryClient.invalidateQueries({queryKey}),onError:(error)=>setMessage(error.message)});
  const removeFile=useMutation({mutationFn:async(fileId:string)=>{const response=await fetch(`/api/client/assessment/files/${fileId}`,{method:"DELETE"});if(!response.ok){const body=await response.json();throw new Error(body.error||"Unable to remove file.");}},onSuccess:()=>queryClient.invalidateQueries({queryKey}),onError:(error)=>setMessage(error.message)});
  useEffect(()=>()=>{if(autosaveRef.current)clearTimeout(autosaveRef.current);},[]);
  useEffect(()=>{const beforeUnload=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue="";}};window.addEventListener("beforeunload",beforeUnload);return()=>window.removeEventListener("beforeunload",beforeUnload);},[dirty]);
  const setValue=(question:AssessmentQuestion,value:AssessmentAnswerValue,immediate=false)=>{const next={...answers,[question.key]:value};setAnswers(next);setDirty(true);setErrors((current)=>({...current,[question.key]:validateQuestion(question,value)||""}));if(autosaveRef.current)clearTimeout(autosaveRef.current);autosaveRef.current=setTimeout(()=>draftMutation.mutate({answers:{[question.key]:value},currentSection:sectionIndex+1}),immediate?0:900);};
  const next=async()=>{const validation=validateSection(section,answers);if(validation.length){setErrors(Object.fromEntries(validation.map((item)=>[item.questionKey,item.message])));setMessage("Complete the required questions before continuing.");return;}try{await completeMutation.mutateAsync();setErrors({});setMessage("");setSectionIndex((value)=>Math.min(value+1,assessment.template.sections.length-1));window.scrollTo({top:0,behavior:"smooth"});}catch(error){setMessage(error instanceof Error?error.message:"Unable to complete section.");}};
  const submit=async()=>{try{const result=await submitMutation.mutateAsync();if(!result.ok){setErrors(Object.fromEntries(result.errors.map((item)=>[item.questionKey,item.message])));const first=assessment.template.sections.findIndex((candidate)=>candidate.questions.some((question)=>result.errors.some((error)=>error.questionKey===question.key)));if(first>=0)setSectionIndex(first);setMessage("Complete all mandatory questions before submission.");return;}router.push("/client/assessment/submitted");}catch(error){setMessage(error instanceof Error?error.message:"Submission failed.");}};
  const finalSection=sectionIndex===assessment.template.sections.length-1;
  return <DocumentShell><DocumentHeader/><main><DocumentContainer className="pt-6 md:pt-9">
    <div className="mb-2 flex items-end justify-between"><div><span className="text-[11px] font-bold uppercase tracking-[.12em] text-[#1d4f7a]">Section {sectionIndex+1} of {assessment.template.sections.length}</span><div className="mt-1 text-sm text-slate-600">{section.title}</div></div><span className="text-xs text-slate-500">{progress}% complete</span></div>
    <div className="mb-6 h-[3px] bg-slate-200"><div className="h-full bg-[#1d4f7a] transition-[width]" style={{width:`${progress}%`}}/></div>
    <form onSubmit={(event)=>event.preventDefault()} className="overflow-hidden rounded-t-md border border-slate-200 bg-white shadow-sm"><header className="border-b border-slate-200 px-5 py-7 md:px-12 md:py-10"><p className="mb-2 text-[11px] font-bold uppercase tracking-[.12em] text-slate-500">{assessment.template.name} · Version {assessment.template.version}</p><h1 className="font-serif text-3xl text-slate-900">{section.title}</h1>{section.description&&<p className="mt-3 max-w-2xl text-sm leading-7 text-slate-600">{section.description}</p>}</header>
      <div className="grid gap-7 px-5 py-7 md:px-12 md:py-10">{finalSection&&<AssessmentSummary assessment={assessment} answers={answers}/>} {section.questions.map((question)=><QuestionRenderer key={question.id} question={question} value={answers[question.key]} error={errors[question.key]} files={assessment.files.filter((file)=>file.questionKey===question.key)} uploading={fileMutation.isPending} onUpload={(file)=>fileMutation.mutate({questionKey:question.key,file})} onRemoveFile={(fileId)=>removeFile.mutate(fileId)} onChange={(value,immediate)=>setValue(question,value,immediate)}/>)}</div>
      {message&&<div role="status" aria-live="polite" className="mx-5 mb-6 border-l-4 border-amber-700 bg-amber-50 px-4 py-3 text-sm text-amber-950 md:mx-12">{message}</div>}
    </form>
    <DocumentActionBar section={sectionIndex} submitting={draftMutation.isPending||completeMutation.isPending||submitMutation.isPending} onPrevious={()=>setSectionIndex((value)=>Math.max(0,value-1))} onSave={()=>draftMutation.mutate({answers,currentSection:sectionIndex+1})} onNext={next} onSubmit={submit}/>
    <DocumentFooter section={sectionIndex} progress={progress} onRestoreDraft={()=>queryClient.invalidateQueries({queryKey})}/>
  </DocumentContainer></main></DocumentShell>;
}

function QuestionRenderer({question,value,error,files,uploading,onChange,onUpload,onRemoveFile}:{question:AssessmentQuestion;value:AssessmentAnswerValue|undefined;error?:string;files:AssessmentFile[];uploading:boolean;onChange:(value:AssessmentAnswerValue,immediate?:boolean)=>void;onUpload:(file:File)=>void;onRemoveFile:(fileId:string)=>void}){
  if(question.fieldType==="summary")return null; const id=`assessment-${question.key}`; const common={id,"aria-invalid":Boolean(error),"aria-describedby":error?`${id}-error`:undefined,className:"min-h-11 w-full rounded border border-slate-300 bg-white px-3 text-sm text-slate-900 outline-none focus:border-[#1d4f7a] focus:ring-2 focus:ring-[#1d4f7a]/10"};
  const label=<><label htmlFor={id} className="text-sm font-semibold text-slate-800">{question.label}{question.required&&<span className="text-red-700"> *</span>}</label>{question.description&&<p className="text-xs leading-5 text-slate-500">{question.description}</p>}</>;
  let control:React.ReactNode;
  if(question.fieldType==="textarea")control=<textarea {...common} rows={6} placeholder={question.placeholder||undefined} value={typeof value==="string"?value:""} onChange={(event)=>onChange(event.target.value)}/>;
  else if(["single_select","radio"].includes(question.fieldType))control=<select {...common} value={typeof value==="string"?value:""} onChange={(event)=>onChange(event.target.value,true)}><option value="">Select an option</option>{question.options.map((option)=><option key={option.id} value={option.value}>{option.label}</option>)}</select>;
  else if(["multi_select","checkbox"].includes(question.fieldType)){const selected=Array.isArray(value)?value:[];control=<fieldset className="grid grid-cols-1 gap-2 sm:grid-cols-2 lg:grid-cols-3"><legend className="sr-only">{question.label}</legend>{question.options.map((option)=><label key={option.id} className={`flex min-h-11 cursor-pointer items-center gap-2 rounded border px-3 py-2 text-sm ${selected.includes(option.value)?"border-[#1d4f7a] bg-[#eef4f8]":"border-slate-300"}`}><input type="checkbox" checked={selected.includes(option.value)} onChange={()=>onChange(selected.includes(option.value)?selected.filter((item)=>item!==option.value):[...selected,option.value],true)}/>{option.label}</label>)}</fieldset>}
  else if(["boolean","consent"].includes(question.fieldType))control=<label className="flex min-h-11 items-start gap-3 rounded border border-slate-300 p-3 text-sm leading-6"><input id={id} type="checkbox" className="mt-1" checked={value===true||value==="yes"} onChange={(event)=>onChange(event.target.checked,true)}/><span>{question.label}</span></label>;
  else if(question.fieldType==="file_upload")control=<div className="grid gap-3"><label className="flex min-h-24 cursor-pointer items-center justify-center rounded border border-dashed border-slate-400 bg-slate-50 p-5 text-center text-sm text-slate-600"><input id={id} className="sr-only" type="file" disabled={uploading} accept=".pdf,.docx,.xlsx,.png,.jpg,.jpeg,.webp,.mp4" onChange={(event)=>{const file=event.target.files?.[0];if(file)onUpload(file);event.target.value="";}}/>{uploading?"Uploading securely…":"Select a PDF, DOCX, XLSX, image or MP4 (maximum 25 MB)"}</label>{files.map((file)=><div key={file.id} className="flex items-center justify-between gap-3 border-b border-slate-200 py-2 text-sm"><span className="truncate">{file.fileName}</span><button type="button" onClick={()=>onRemoveFile(file.id)} className="min-h-11 px-2 text-xs font-semibold text-red-700">Remove</button></div>)}</div>;
  else control=<input {...common} type={question.fieldType==="signature"?"text":question.fieldType} placeholder={question.placeholder||undefined} value={typeof value==="string"||typeof value==="number"?value:""} onChange={(event)=>onChange(question.fieldType==="number"?Number(event.target.value):event.target.value)}/>;
  return <div className="grid gap-2">{question.fieldType!=="consent"&&label}{control}{question.helpText&&<p className="text-xs leading-5 text-slate-500">{question.helpText}</p>}{error&&<p id={`${id}-error`} role="alert" className="text-xs font-medium text-red-700">{error}</p>}</div>;
}

function hasAnswer(value:AssessmentAnswerValue|undefined){return value!==undefined&&value!==null&&value!==""&&(!Array.isArray(value)||value.length>0);}
function AssessmentSummary({assessment,answers}:{assessment:ClientAssessment;answers:Record<string,AssessmentAnswerValue>}){const rows=useMemo(()=>assessment.template.sections.slice(0,-1).map((section)=>({section,items:section.questions.filter((question)=>hasAnswer(answers[question.key]))})),[assessment.template.sections,answers]);return <section className="grid gap-5 border-b border-slate-200 pb-8"><h2 className="font-serif text-2xl">Final Review</h2>{rows.map(({section,items})=><div key={section.id}><h3 className="mb-2 text-sm font-bold text-slate-800">{section.position}. {section.title}</h3><dl className="divide-y divide-slate-200 border border-slate-200">{items.map((question)=><div key={question.id} className="grid gap-1 p-3 md:grid-cols-[220px_1fr]"><dt className="text-xs font-semibold text-slate-600">{question.label}</dt><dd className="text-sm text-slate-800">{Array.isArray(answers[question.key])?(answers[question.key] as string[]).map((value)=>question.options.find((option)=>option.value===value)?.label||value).join(", "):String(answers[question.key])}</dd></div>)}</dl></div>)}</section>}
