"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { Building2, CircleAlert, Layers3, Loader2, Plus, RefreshCw, X } from "lucide-react";

type Item = { id:string; name:string; code:string; status:string; parent_id?:string|null; level?:number|null };
type Kind = "departments" | "designations";

export default function StructureWorkspace({kind}:{kind:Kind}) {
  const [items,setItems]=useState<Item[]>([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[saving,setSaving]=useState(false);
  const [error,setError]=useState(""),[name,setName]=useState(""),[code,setCode]=useState(""),[level,setLevel]=useState("");
  const title=kind==="departments"?"Departments":"Designations";
  const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch(`/api/v1/hrms/people/${kind}`);const data=await response.json();if(!response.ok)throw new Error(data.detail||data.error);setItems(data.items||[])}catch(e){setError(e instanceof Error?e.message:"Unable to load records")}finally{setLoading(false)}},[kind]);
  useEffect(()=>{void load()},[load]);
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError("");try{const response=await fetch(`/api/v1/hrms/people/${kind}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,code,...(kind==="designations"&&level?{level:Number(level)}:{}),status:"active"})});const data=response.status===204?{}:await response.json();if(!response.ok)throw new Error(data.detail||data.error);setOpen(false);setName("");setCode("");setLevel("");await load()}catch(e){setError(e instanceof Error?e.message:"Unable to save record")}finally{setSaving(false)}}
  return <div className="space-y-6">
    <header className="flex items-end justify-between border-b border-[var(--border-subtle)] pb-6"><div><div className="mb-2 text-[10px] font-bold uppercase tracking-[.18em] text-[#0075de]">People Core · Organisation</div><h1 className="text-3xl font-extrabold tracking-tight">{title}</h1><p className="mt-2 text-xs text-[var(--text-secondary)]">Maintain the organisation hierarchy and active workforce structure.</p></div><button onClick={()=>setOpen(true)} className="inline-flex h-9 items-center gap-2 rounded-lg bg-[#0075de] px-3 text-[11px] font-bold text-white"><Plus size={14}/> Add {kind==="departments"?"department":"designation"}</button></header>
    {error&&<div className="flex items-center gap-2 rounded-xl border border-red-500/20 bg-red-500/5 px-4 py-3 text-xs text-red-600"><CircleAlert size={15}/>{error}<button onClick={()=>void load()} className="ml-auto"><RefreshCw size={14}/></button></div>}
    <section className="overflow-hidden rounded-xl border border-[var(--border-subtle)] bg-[var(--card)]">
      <div className="grid grid-cols-[1fr_160px_120px] bg-[var(--surface-2)] px-4 py-3 text-[9px] font-bold uppercase tracking-wider text-[var(--text-muted)]"><span>Name</span><span>{kind==="departments"?"Code":"Level"}</span><span>Status</span></div>
      {loading?Array.from({length:4}).map((_,i)=><div key={i} className="m-4 h-10 animate-pulse rounded bg-[var(--surface-2)]"/>):items.map(item=><div key={item.id} className="grid grid-cols-[1fr_160px_120px] items-center border-t border-[var(--border-subtle)] px-4 py-4 text-xs"><div className="flex items-center gap-3">{kind==="departments"?<Building2 size={15} className="text-[#0075de]"/>:<Layers3 size={15} className="text-[#0075de]"/>}<div><b>{item.name}</b><p className="mt-0.5 text-[10px] text-[var(--text-muted)]">{item.code}</p></div></div><span>{kind==="departments"?item.code:item.level||"—"}</span><span className="w-fit rounded-full bg-emerald-500/10 px-2 py-1 text-[9px] font-bold capitalize text-emerald-600">{item.status}</span></div>)}
      {!loading&&!items.length&&!error&&<div className="py-16 text-center text-xs text-[var(--text-muted)]">No {kind} have been configured.</div>}
    </section>
    {open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 p-4" onClick={()=>setOpen(false)}><form onSubmit={submit} onClick={e=>e.stopPropagation()} className="w-full max-w-md rounded-2xl border border-[var(--border-subtle)] bg-[var(--card)] p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-lg font-extrabold">New {kind==="departments"?"department":"designation"}</h2><button type="button" onClick={()=>setOpen(false)}><X size={17}/></button></div><div className="mt-6 space-y-4">{[["Name",name,setName],["Code",code,setCode]].map(([label,value,setter])=><label key={String(label)} className="block text-[10px] font-bold uppercase tracking-wider text-[var(--text-muted)]">{String(label)}<input required value={String(value)} onChange={e=>(setter as (v:string)=>void)(e.target.value)} className="mt-1.5 h-10 w-full rounded-lg border border-[var(--border-subtle)] bg-[var(--surface-1)] px-3 text-xs font-medium normal-case tracking-normal text-[var(--text-primary)] outline-none focus:border-[#0075de]"/></label>)}{kind==="designations"&&<label className="block text-[10px] font-bold uppercase tracking-wider text-[var(--text-muted)]">Level<input type="number" min="1" value={level} onChange={e=>setLevel(e.target.value)} className="mt-1.5 h-10 w-full rounded-lg border border-[var(--border-subtle)] bg-[var(--surface-1)] px-3 text-xs text-[var(--text-primary)]"/></label>}</div><button disabled={saving} className="mt-6 inline-flex h-10 w-full items-center justify-center gap-2 rounded-lg bg-[#0075de] text-xs font-bold text-white disabled:opacity-50">{saving&&<Loader2 size={14} className="animate-spin"/>}Create {kind==="departments"?"department":"designation"}</button></form></div>}
  </div>
}
