"use client";
import { useState } from "react";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
type Item={id:string;question_key:string;instruction:string|null;reason:string;is_required:boolean;original_answer_snapshot:unknown;question_snapshot:Record<string,unknown>;status:string}; type RequestData={request_number:string;general_message:string;due_at:string|null;assessment_information_request_items:Item[]};
async function load(id:string){const r=await fetch(`/api/client/assessment/information-request/${id}`,{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error);return b.request as RequestData;}
function valueText(value:unknown){return Array.isArray(value)?value.join(", "):value==null?"":String(value);}
function Editor({item,onSave}:{item:Item;onSave:(value:unknown,note:string)=>void}){const snapshot=item.question_snapshot;const type=String(snapshot.fieldType||snapshot.field_type||"text");const options=Array.isArray(snapshot.options)?snapshot.options as Array<{value:string;label:string}>:[];const [value,setValue]=useState<unknown>(item.original_answer_snapshot??"");const [note,setNote]=useState("");const multi=type==="multi_select"||type==="checkbox";const selected=Array.isArray(value)?value as string[]:[];if(["single_select","radio"].includes(type))return <><select value={String(value||"")} onChange={e=>setValue(e.target.value)} className="min-h-11 w-full rounded border border-slate-300 px-3"><option value="">Select an option</option>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select><Save onClick={()=>onSave(value,note)}/></>;if(multi)return <><div className="grid gap-2 sm:grid-cols-2">{options.map(o=><label key={o.value} className="flex items-center gap-2 rounded border border-slate-200 p-3 text-sm"><input type="checkbox" checked={selected.includes(o.value)} onChange={e=>setValue(e.target.checked?[...selected,o.value]:selected.filter(v=>v!==o.value))}/>{o.label}</label>)}</div><Save onClick={()=>onSave(value,note)}/></>;const inputType=type==="email"?"email":type==="number"?"number":type==="date"?"date":type==="phone"?"tel":"text";return <><textarea rows={type==="textarea"?5:2} value={String(value??"")} onChange={e=>setValue(inputType==="number"?Number(e.target.value):e.target.value)} className="w-full rounded border border-slate-300 p-3"/><label className="mt-3 block text-sm"><span className="font-semibold">Note (optional)</span><textarea rows={2} value={note} onChange={e=>setNote(e.target.value)} className="mt-1 w-full rounded border border-slate-300 p-2"/></label><Save onClick={()=>onSave(value,note)}/></>}
function Save({onClick}:{onClick:()=>void}){return <button type="button" onClick={onClick} className="mt-3 min-h-10 rounded bg-[#1d4f7a] px-4 text-sm font-semibold text-white">Save response</button>}
export default function InformationRequestPage({params}:{params:Promise<{requestId:string}>}){const [id]=useState(()=>"pending");const [requestId,setRequestId]=useState("");const client=useQueryClient();void params.then(p=>setRequestId(p.requestId));const query=useQuery({queryKey:["client","information-request",requestId],queryFn:()=>load(requestId),enabled:Boolean(requestId)});const mutation=useMutation({mutationFn:async(input:{itemId:string;value:unknown;supportingNote?:string})=>{const r=await fetch(`/api/client/assessment/information-request/${requestId}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(input)});const b=await r.json();if(!r.ok)throw new Error(b.error);return b;},onSuccess:()=>client.invalidateQueries({queryKey:["client","information-request",requestId]})});if(!requestId||query.isPending)return <p>Loading requested information…</p>;if(query.error)return <p role="alert" className="text-red-700">{query.error.message}</p>;return <main className="mx-auto max-w-3xl space-y-6"><header><p className="text-xs font-bold uppercase tracking-wider text-slate-500">{query.data.request_number}</p><h1 className="mt-2 text-3xl font-bold">Provide Requested Information</h1><p className="mt-3 text-slate-600">{query.data.general_message||"Please review and update the requested items below."}</p>{query.data.due_at&&<p className="mt-2 text-sm font-semibold text-amber-700">Due {new Date(query.data.due_at).toLocaleDateString()}</p>}</header>{query.data.assessment_information_request_items.map(item=><section key={item.id} className="rounded-xl border border-slate-200 bg-white p-6"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">{item.reason}</p><h2 className="mt-2 text-xl font-semibold">{String(item.question_snapshot.label||item.question_key)}</h2>{item.instruction&&<p className="mt-2 rounded bg-blue-50 p-3 text-sm text-blue-900">Why we need this: {item.instruction}</p>}<p className="mt-4 text-sm"><span className="font-semibold">Previous answer:</span> {valueText(item.original_answer_snapshot)||"No answer submitted"}</p>{item.status!=="accepted"&&<div className="mt-4"><p className="mb-2 text-sm font-semibold">Updated answer</p><Editor item={item} onSave={(value,note)=>mutation.mutate({itemId:item.id,value,supportingNote:note})}/></div>}<p className="mt-3 text-xs font-semibold uppercase tracking-wider text-slate-500">Status: {item.status.replaceAll("_"," ")}</p></section>)}</main>}

