import { supabaseAdmin } from "@/lib/supabase/admin";
import { HRMSError, type HRMSContext } from "@/lib/hrms/shared/context";
import type { AttendanceEvent, AttendancePolicySnapshot, ShiftSnapshot } from "./contracts";

const attendance=supabaseAdmin.schema("attendance");
const people=supabaseAdmin.schema("people");
const unwrap=<T>(data:T|null,error:{message:string}|null):T=>{if(error)throw new HRMSError(422,"database_error",error.message);return data as T};
export async function selfEmployee(context:HRMSContext){const result=await people.from("employees").select("id,employee_number,first_name,last_name").eq("organisation_id",context.organisationId).eq("user_id",context.userId).is("deleted_at",null).single();return unwrap(result.data,result.error)}
export async function recordEvent(context:HRMSContext,input:{eventType:string;occurredAt:string;source:string;timezone:string;latitude?:number;longitude?:number;accuracyMetres?:number;capturedAt?:string;deviceId?:string;notes?:string;metadata?:Record<string,unknown>;idempotencyKey:string;ipAddress?:string}){const result=await attendance.rpc("record_event",{p_organisation_id:context.organisationId,p_actor_user_id:context.userId,p_event_type:input.eventType,p_occurred_at:input.occurredAt,p_source:input.source,p_timezone:input.timezone,p_latitude:input.latitude??null,p_longitude:input.longitude??null,p_accuracy_metres:input.accuracyMetres??null,p_captured_at:input.capturedAt??null,p_ip_address:input.ipAddress??null,p_device_id:input.deviceId??null,p_notes:input.notes??null,p_metadata:input.metadata||{},p_request_id:context.requestId,p_idempotency_key:input.idempotencyKey});return unwrap(result.data,result.error)}
type EventRow={id:string;event_type:AttendanceEvent["eventType"];occurred_at:string;metadata?:Record<string,unknown>};
type PolicyRow={id:string;standard_minutes:number;full_day_minutes:number;half_day_minutes:number;grace_minutes:number;overtime_after_minutes:number;paid_break_minutes:number;rounding_minutes:number;gps_required:boolean;geofence_required:boolean};
type ShiftRow={id:string;start_time:string;end_time:string;expected_minutes:number;crosses_midnight:boolean};
type SummaryResult={firstCheckIn?:unknown;lastCheckOut?:unknown;scheduledMinutes?:unknown;workedMinutes?:unknown;breakMinutes?:unknown;overtimeMinutes?:unknown;lateMinutes?:unknown;earlyDepartureMinutes?:unknown;status?:unknown;violations?:unknown};
type RegularisationInput={workDate:string;reasonType:string;requestedCheckIn?:string;requestedCheckOut?:string;reason:string};
type DecisionInput={decision:string;comment?:string};
export async function eventsForDay(context:HRMSContext,employeeId:string,start:string,end:string){const result=await attendance.from("events").select("id,event_type,occurred_at,source,timezone,notes,metadata").eq("organisation_id",context.organisationId).eq("employee_id",employeeId).gte("occurred_at",start).lt("occurred_at",end).order("occurred_at");return (unwrap(result.data,result.error) as EventRow[]).map((row):AttendanceEvent=>({id:row.id,eventType:row.event_type,occurredAt:row.occurred_at,metadata:row.metadata}))}
export async function summaries(context:HRMSContext,employeeId:string,from:string,to:string){const result=await attendance.from("daily_summaries").select("*").eq("organisation_id",context.organisationId).eq("employee_id",employeeId).gte("work_date",from).lte("work_date",to).order("work_date");return unwrap(result.data,result.error)}
export async function resolvePolicy(context:HRMSContext,employeeId:string,workDate:string):Promise<AttendancePolicySnapshot&{versionId:string}> {const employee=await people.from("employment_records").select("department_id").eq("organisation_id",context.organisationId).eq("employee_id",employeeId).is("valid_to",null).single();const departmentId=unwrap(employee.data,employee.error).department_id;const assignment=await attendance.from("policy_assignments").select("policy_id").eq("organisation_id",context.organisationId).or(`employee_id.eq.${employeeId},department_id.eq.${departmentId}`).lte("effective_from",workDate).or(`effective_to.is.null,effective_to.gte.${workDate}`).order("employee_id",{ascending:false,nullsFirst:false}).order("effective_from",{ascending:false}).limit(1).single();const policyId=unwrap(assignment.data,assignment.error).policy_id;const version=await attendance.from("policy_versions").select("*").eq("organisation_id",context.organisationId).eq("policy_id",policyId).lte("effective_from",workDate).or(`effective_to.is.null,effective_to.gte.${workDate}`).order("version",{ascending:false}).limit(1).single();const row=unwrap(version.data,version.error) as PolicyRow;return{id:policyId,versionId:row.id,standardMinutes:row.standard_minutes,fullDayMinutes:row.full_day_minutes,halfDayMinutes:row.half_day_minutes,graceMinutes:row.grace_minutes,overtimeAfterMinutes:row.overtime_after_minutes,paidBreakMinutes:row.paid_break_minutes,roundingMinutes:row.rounding_minutes,gpsRequired:row.gps_required,geofenceRequired:row.geofence_required}}
export async function validateGeofence(context:HRMSContext,employeeId:string,date:string,latitude:number,longitude:number){
  const employment=await people.from("employment_records").select("department_id").eq("organisation_id",context.organisationId).eq("employee_id",employeeId).is("valid_to",null).single();
  const departmentId=unwrap(employment.data,employment.error).department_id;
  const assignment=await attendance.from("geofence_assignments").select("geofence_id").eq("organisation_id",context.organisationId).or(`employee_id.eq.${employeeId},department_id.eq.${departmentId}`).lte("effective_from",date).or(`effective_to.is.null,effective_to.gte.${date}`).order("employee_id",{ascending:false,nullsFirst:false}).limit(1).single();
  const fence=await attendance.from("geofences").select("centre_latitude,centre_longitude,radius_metres").eq("organisation_id",context.organisationId).eq("id",unwrap(assignment.data,assignment.error).geofence_id).eq("status","active").single();
  const row=unwrap(fence.data,fence.error),radians=(value:number)=>value*Math.PI/180,dLat=radians(latitude-Number(row.centre_latitude)),dLon=radians(longitude-Number(row.centre_longitude));
  const a=Math.sin(dLat/2)**2+Math.cos(radians(Number(row.centre_latitude)))*Math.cos(radians(latitude))*Math.sin(dLon/2)**2;
  if(6_371_000*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a))>Number(row.radius_metres))throw new HRMSError(422,"outside_geofence","Clock location is outside the assigned geofence");
}
export async function resolveShift(context:HRMSContext,employeeId:string,workDate:string):Promise<ShiftSnapshot>{const employment=await people.from("employment_records").select("department_id").eq("employee_id",employeeId).eq("organisation_id",context.organisationId).is("valid_to",null).single();const departmentId=unwrap(employment.data,employment.error).department_id;const assignment=await attendance.from("shift_assignments").select("shift_id").eq("organisation_id",context.organisationId).or(`employee_id.eq.${employeeId},department_id.eq.${departmentId}`).lte("effective_from",workDate).or(`effective_to.is.null,effective_to.gte.${workDate}`).order("employee_id",{ascending:false,nullsFirst:false}).limit(1).maybeSingle();if(!assignment.data)return{expectedMinutes:0,crossesMidnight:false};const shift=await attendance.from("shifts").select("*").eq("id",assignment.data.shift_id).eq("organisation_id",context.organisationId).single();const row=unwrap(shift.data,shift.error) as ShiftRow;return{id:row.id,expectedStart:row.start_time,expectedEnd:row.end_time,expectedMinutes:row.expected_minutes,crossesMidnight:row.crosses_midnight}}
export async function upsertSummary(context:HRMSContext,employeeId:string,workDate:string,policyVersionId:string,shift:ShiftSnapshot,result:SummaryResult){const payload={organisation_id:context.organisationId,employee_id:employeeId,work_date:workDate,policy_version_id:policyVersionId,shift_id:shift.id||null,first_check_in:result.firstCheckIn,last_check_out:result.lastCheckOut,scheduled_minutes:result.scheduledMinutes,worked_minutes:result.workedMinutes,break_minutes:result.breakMinutes,overtime_minutes:result.overtimeMinutes,late_minutes:result.lateMinutes,early_departure_minutes:result.earlyDepartureMinutes,status:result.status,violations:result.violations,calculation_version:1,calculated_at:new Date().toISOString(),updated_at:new Date().toISOString()};const response=await attendance.from("daily_summaries").upsert(payload,{onConflict:"organisation_id,employee_id,work_date"}).select().single();return unwrap(response.data,response.error)}
export async function submitRegularisation(context:HRMSContext,input:RegularisationInput){const response=await attendance.rpc("submit_regularisation",{p_organisation_id:context.organisationId,p_actor_user_id:context.userId,p_work_date:input.workDate,p_reason_type:input.reasonType,p_requested_check_in:input.requestedCheckIn||null,p_requested_check_out:input.requestedCheckOut||null,p_reason:input.reason,p_request_id:context.requestId});return unwrap(response.data,response.error)}
export async function decideRegularisation(context:HRMSContext,id:string,input:DecisionInput){const response=await attendance.rpc("decide_regularisation",{p_organisation_id:context.organisationId,p_actor_user_id:context.userId,p_regularisation_id:id,p_decision:input.decision,p_comment:input.comment||"",p_request_id:context.requestId});return unwrap(response.data,response.error)}
export {attendance,people,unwrap};
