import "server-only";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { supabaseAdmin } from "@/lib/supabase/admin";

export class AdminSalesError extends Error{constructor(public status:number,message:string){super(message)}}
type Capability="sales.team.view"|"sales.assignment.manage"|"sales.qualification.review"|"sales.discovery.manage"|"sales.handoff.review"|"employee.access.manage";
export type AdminSalesContext={userId:string;organisationId:string;employeeId:string|null;scope:"organisation"|"team";permissions:Set<string>};

export async function requireAdminSales(capability:Capability):Promise<AdminSalesContext>{const session=await getServerSession(authOptions);if(!session?.user?.id)throw new AdminSalesError(401,"Authentication required");if(!session.user.organisation_id)throw new AdminSalesError(403,"Organisation context required");const permissions=new Set(session.user.permissions||[]),platformAdmin=session.user.role==="ADMIN";if(!platformAdmin&&!permissions.has(capability))throw new AdminSalesError(403,`Permission required: ${capability}`);const identity=await supabaseAdmin.schema("identity").from("employee_identities").select("employee_id").eq("organisation_id",session.user.organisation_id).eq("auth_user_id",session.user.id).maybeSingle();return{userId:session.user.id,organisationId:session.user.organisation_id,employeeId:identity.data?.employee_id||null,scope:platformAdmin?"organisation":"team",permissions}}
async function scopedEmployeeIds(context:AdminSalesContext){if(context.scope==="organisation")return null;if(!context.employeeId)return[];const reports=await supabaseAdmin.schema("people").from("employment_records").select("employee_id").eq("organisation_id",context.organisationId).eq("manager_employee_id",context.employeeId).is("valid_to",null);return(reports.data||[]).map(row=>row.employee_id)}
export function adminSalesResponse(error:unknown){if(error instanceof AdminSalesError)return Response.json({error:error.message,code:error.status===403?"permission_denied":"admin_sales_request_invalid"},{status:error.status});return Response.json({error:"Admin sales operation failed",code:"admin_sales_operation_failed"},{status:500})}

export async function getAdminSalesOverview(period:"today"|"week"|"month"="week"){
  const context=await requireAdminSales("sales.team.view"),scope=await scopedEmployeeIds(context),now=Date.now(),since=new Date(now-(period==="today"?86400000:period==="week"?7*86400000:30*86400000)).toISOString();
  if(scope&&scope.length===0)return{context,employees:[],leads:[],handoffs:[],meetings:[],metrics:{assigned:0,overdue:0,qualified:0,discovery:0,handoffs:0,untouched:0}};
  let employeeQuery=supabaseAdmin.schema("people").from("employees").select("id,first_name,last_name,user_id").eq("organisation_id",context.organisationId).is("deleted_at",null);if(scope)employeeQuery=employeeQuery.in("id",scope);
  const employees=(await employeeQuery).data||[],employeeIds=employees.map(e=>e.id);if(!employeeIds.length)return{context,employees:[],leads:[],handoffs:[],meetings:[],metrics:{assigned:0,overdue:0,qualified:0,discovery:0,handoffs:0,untouched:0}};
  const [leadsR,unassignedR,activitiesR,qualificationsR,followupsR,opportunitiesR,meetingsR,handoffsR,historiesR]=await Promise.all([
    supabaseAdmin.from("leads").select("id,business_name,name,email,phone,status,priority,assigned_employee_id,assigned_at,updated_at,created_at").eq("organisation_id",context.organisationId).in("assigned_employee_id",employeeIds).is("deleted_at",null).order("updated_at",{ascending:false}).limit(500),
    context.scope==="organisation"?supabaseAdmin.from("leads").select("id,business_name,name,email,phone,status,priority,created_at").eq("organisation_id",context.organisationId).is("assigned_employee_id",null).is("deleted_at",null).order("created_at",{ascending:false}).limit(200):Promise.resolve({data:[]}),
    supabaseAdmin.from("sales_activities").select("id,lead_id,employee_id,activity_type,occurred_at,outcome").eq("organisation_id",context.organisationId).in("employee_id",employeeIds).gte("occurred_at",since).order("occurred_at",{ascending:false}).limit(1000),
    supabaseAdmin.from("lead_qualifications").select("*").eq("organisation_id",context.organisationId).in("employee_id",employeeIds),
    supabaseAdmin.from("sales_followups").select("id,lead_id,assigned_employee_id,status,due_at,completed_at,context").eq("organisation_id",context.organisationId).in("assigned_employee_id",employeeIds),
    supabaseAdmin.from("sales_opportunities").select("id,originating_lead_id,owner_employee_id,name,stage,qualification_summary,created_at,updated_at").eq("organisation_id",context.organisationId).in("owner_employee_id",employeeIds),
    supabaseAdmin.from("sales_discovery_schedules").select("*").eq("organisation_id",context.organisationId).in("scheduled_by_employee_id",employeeIds).order("scheduled_start"),
    supabaseAdmin.from("sales_handoffs").select("*").eq("organisation_id",context.organisationId).in("handed_off_by_employee_id",employeeIds).order("handed_off_at",{ascending:false}),
    supabaseAdmin.from("lead_assignment_history").select("*").eq("organisation_id",context.organisationId).in("assigned_employee_id",employeeIds).order("assigned_at",{ascending:false}).limit(500)
  ]);
  const identities=(await supabaseAdmin.schema("identity").from("employee_identities").select("employee_id,workspace_status,updated_at").eq("organisation_id",context.organisationId).in("employee_id",employeeIds)).data||[];
  const leads=leadsR.data||[],activities=activitiesR.data||[],qualifications=qualificationsR.data||[],followups=followupsR.data||[],opportunities=opportunitiesR.data||[],meetings=meetingsR.data||[],handoffs=handoffsR.data||[],activityLeads=new Set(activities.map(a=>a.lead_id));
  const team=employees.map(employee=>{const assigned=leads.filter(l=>l.assigned_employee_id===employee.id),leadIds=new Set(assigned.map(l=>l.id)),firstActions=activities.filter(a=>a.employee_id===employee.id),responseTimes=assigned.map(l=>{const first=firstActions.filter(a=>a.lead_id===l.id).sort((a,b)=>Date.parse(a.occurred_at)-Date.parse(b.occurred_at))[0];return first&&l.assigned_at?Date.parse(first.occurred_at)-Date.parse(l.assigned_at):null}).filter((v):v is number=>v!==null&&v>=0),identity=identities.find(i=>i.employee_id===employee.id);return{id:employee.id,name:`${employee.first_name} ${employee.last_name}`.trim(),workspaceStatus:identity?.workspace_status||"not_provisioned",assigned:assigned.length,contacted:new Set(firstActions.map(a=>a.lead_id)).size,qualifying:qualifications.filter(q=>q.employee_id===employee.id&&["researching","contacting","engaged","qualifying"].includes(q.state)).length,qualified:opportunities.filter(o=>o.owner_employee_id===employee.id).length,discovery:meetings.filter(m=>m.scheduled_by_employee_id===employee.id&&m.status==="scheduled").length,handoffs:handoffs.filter(h=>h.handed_off_by_employee_id===employee.id).length,overdue:followups.filter(f=>f.assigned_employee_id===employee.id&&f.status==="open"&&Date.parse(f.due_at)<now).length,dueToday:followups.filter(f=>f.assigned_employee_id===employee.id&&f.status==="open"&&new Date(f.due_at).toDateString()===new Date().toDateString()).length,activities:firstActions.length,averageFirstActionHours:responseTimes.length?Math.round(responseTimes.reduce((a,b)=>a+b,0)/responseTimes.length/3600000):null,leadIds:[...leadIds]}});
  const leadById=new Map(leads.map(l=>[l.id,l])),employeeById=new Map(team.map(e=>[e.id,e]));
  const detailedLeads=leads.map(lead=>{const leadActivities=activities.filter(a=>a.lead_id===lead.id),next=followups.filter(f=>f.lead_id===lead.id&&f.status==="open").sort((a,b)=>Date.parse(a.due_at)-Date.parse(b.due_at))[0],qualification=qualifications.find(q=>q.lead_id===lead.id),opportunity=opportunities.find(o=>o.originating_lead_id===lead.id);return{...lead,employeeName:employeeById.get(lead.assigned_employee_id)?.name||"Unassigned",lastActivity:leadActivities[0]?.occurred_at||null,nextFollowup:next?.due_at||null,qualification,opportunity,staleReason:!leadActivities.length?"No employee action":next&&Date.parse(next.due_at)<now?"Follow-up overdue":qualification?.state==="qualifying"&&Date.parse(qualification.updated_at)<now-7*86400000?"Qualification stalled":opportunity?.stage==="qualified"&&!meetings.some(m=>m.opportunity_id===opportunity.id)?"Qualified without discovery":null}});
  return{context,employees:team,leads:detailedLeads,unassigned:unassignedR.data||[],handoffs:handoffs.map(h=>({...h,lead:leadById.get(h.lead_id),employeeName:employeeById.get(h.handed_off_by_employee_id)?.name||"Unknown",opportunity:opportunities.find(o=>o.id===h.opportunity_id),meeting:meetings.find(m=>m.id===h.discovery_schedule_id)})),meetings:meetings.map(m=>({...m,employeeName:employeeById.get(m.scheduled_by_employee_id)?.name||"Unknown",opportunity:opportunities.find(o=>o.id===m.opportunity_id)})),histories:historiesR.data||[],metrics:{assigned:leads.length,newAssignments:leads.filter(l=>Date.parse(l.assigned_at||"")>=Date.parse(since)).length,overdue:followups.filter(f=>f.status==="open"&&Date.parse(f.due_at)<now).length,qualified:opportunities.length,discovery:meetings.filter(m=>m.status==="scheduled").length,handoffs:handoffs.length,untouched:leads.filter(l=>!activityLeads.has(l.id)).length,awaitingHandoff:handoffs.filter(h=>h.review_status==="awaiting_review").length}};
}

export async function assignSalesLeads(input:{leadIds:string[];employeeId:string;priority?:string;assignmentNote?:string;initialDueAt?:string}){const context=await requireAdminSales("sales.assignment.manage"),scope=await scopedEmployeeIds(context);if(scope&&!scope.includes(input.employeeId))throw new AdminSalesError(403,"Employee is outside your management scope");if(!input.leadIds.length||input.leadIds.length>100)throw new AdminSalesError(422,"Select between 1 and 100 prospects");if(input.priority&&!['low','medium','high','urgent'].includes(input.priority))throw new AdminSalesError(422,"Invalid priority");const {data,error}=await supabaseAdmin.rpc("admin_assign_sales_leads",{p_organisation_id:context.organisationId,p_lead_ids:input.leadIds,p_employee_id:input.employeeId,p_actor_user_id:context.userId,p_priority:input.priority||null,p_assignment_note:input.assignmentNote||null,p_initial_due_at:input.initialDueAt||null});if(error)throw new AdminSalesError(409,error.message);await supabaseAdmin.schema("audit").from("events").insert(input.leadIds.map(id=>({organisation_id:context.organisationId,actor_user_id:context.userId,entity_type:"lead",entity_id:id,action:"lead_assigned",new_value:{employeeId:input.employeeId,priority:input.priority||null},request_id:crypto.randomUUID()})));return{assigned:Number(data||0)}}
export async function reviewSalesHandoff(input:{handoffId:string;action:"accept"|"request_clarification";internalOwnerEmployeeId?:string;message?:string}){const context=await requireAdminSales("sales.handoff.review"),scope=await scopedEmployeeIds(context);if(scope){const handoff=await supabaseAdmin.from("sales_handoffs").select("handed_off_by_employee_id").eq("id",input.handoffId).eq("organisation_id",context.organisationId).maybeSingle();if(!handoff.data||!scope.includes(handoff.data.handed_off_by_employee_id))throw new AdminSalesError(404,"Handoff not found")}const {data,error}=await supabaseAdmin.rpc("admin_review_sales_handoff",{p_organisation_id:context.organisationId,p_handoff_id:input.handoffId,p_actor_user_id:context.userId,p_action:input.action,p_internal_owner_employee_id:input.internalOwnerEmployeeId||null,p_message:input.message||null});if(error)throw new AdminSalesError(409,error.message);await supabaseAdmin.schema("audit").from("events").insert({organisation_id:context.organisationId,actor_user_id:context.userId,entity_type:"sales_handoff",entity_id:input.handoffId,action:input.action==="accept"?"handoff_accepted":"handoff_clarification_requested",new_value:{internalOwnerEmployeeId:input.internalOwnerEmployeeId||null},request_id:crypto.randomUUID()});return data}
export async function reviewSalesQualification(input:{leadId:string;action:"approve"|"request_clarification";message?:string}){const context=await requireAdminSales("sales.qualification.review"),scope=await scopedEmployeeIds(context),qualification=await supabaseAdmin.from("lead_qualifications").select("id,employee_id,review_state").eq("organisation_id",context.organisationId).eq("lead_id",input.leadId).maybeSingle();if(!qualification.data||(scope&&!scope.includes(qualification.data.employee_id)))throw new AdminSalesError(404,"Qualification not found");if(input.action==="request_clarification"&&!input.message?.trim())throw new AdminSalesError(422,"Clarification context is required");const state=input.action==="approve"?"approved":"needs_clarification",updated=await supabaseAdmin.from("lead_qualifications").update({review_state:state,manager_feedback:input.message?.trim()||null,reviewed_by:context.userId,reviewed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",qualification.data.id).eq("organisation_id",context.organisationId).select("*").single();if(updated.error)throw new AdminSalesError(500,"Qualification review failed");if(input.action==="request_clarification"){await supabaseAdmin.from("sales_management_feedback").insert({organisation_id:context.organisationId,employee_id:qualification.data.employee_id,lead_id:input.leadId,feedback_type:"qualification",message:input.message!.trim(),created_by:context.userId});const employee=await supabaseAdmin.schema("people").from("employees").select("user_id").eq("id",qualification.data.employee_id).eq("organisation_id",context.organisationId).single();if(employee.data?.user_id)await supabaseAdmin.schema("notifications").from("notifications").insert({organisation_id:context.organisationId,recipient_user_id:employee.data.user_id,template_key:"sales_qualification_clarification",payload:{title:"Qualification needs clarification",message:input.message!.trim(),href:`/workspace/sales/leads/${input.leadId}`,eventKey:`qualification-clarification:${qualification.data.id}:${Date.now()}`}})}await supabaseAdmin.schema("audit").from("events").insert({organisation_id:context.organisationId,actor_user_id:context.userId,entity_type:"lead_qualification",entity_id:qualification.data.id,action:input.action==="approve"?"qualification_approved":"qualification_clarification_requested",new_value:{reviewState:state},request_id:crypto.randomUUID()});return updated.data}
export async function setEmployeeWorkspaceStatus(employeeId:string,status:"active"|"suspended"){const context=await requireAdminSales("employee.access.manage"),scope=await scopedEmployeeIds(context);if(scope&&!scope.includes(employeeId))throw new AdminSalesError(403,"Employee is outside your management scope");const existing=await supabaseAdmin.schema("identity").from("employee_identities").select("id,workspace_status").eq("organisation_id",context.organisationId).eq("employee_id",employeeId).maybeSingle();if(!existing.data)throw new AdminSalesError(404,"Employee workspace not found");const updated=await supabaseAdmin.schema("identity").from("employee_identities").update({workspace_status:status,suspended_at:status==="suspended"?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq("id",existing.data.id).eq("organisation_id",context.organisationId).select("id,workspace_status").single();if(updated.error)throw new AdminSalesError(500,"Workspace update failed");await supabaseAdmin.schema("audit").from("events").insert({organisation_id:context.organisationId,actor_user_id:context.userId,entity_type:"employee_identity",entity_id:existing.data.id,action:status==="active"?"workspace_activated":"workspace_suspended",old_value:{status:existing.data.workspace_status},new_value:{status},request_id:crypto.randomUUID()});return updated.data}
