import "server-only";
import type { EmployeeContext } from "./context";
import { supabaseAdmin } from "@/lib/supabase/admin";
import { getAssignedLeads } from "./sales-service";

export type WorkSourceType="crm_followup"|"assigned_lead"|"qualification"|"discovery_meeting"|"handoff"|"onboarding"|"hr_action";
export type UnifiedWorkItem={id:string;sourceType:WorkSourceType;sourceId:string;category:string;title:string;description:string;entityName:string;dueAt:string|null;priority:"urgent"|"high"|"medium"|"low";status:"open"|"completed";actionType:string;href:string;createdAt:string;metadataSafe:Record<string,unknown>;rank:number};
export type WorkView="today"|"upcoming"|"overdue"|"completed"|"all";
const startOfToday=()=>{const d=new Date();d.setHours(0,0,0,0);return d.getTime()},endOfToday=()=>{const d=new Date();d.setHours(23,59,59,999);return d.getTime()};
export async function getEmployeeWorkQueue(context:EmployeeContext,view:WorkView="today"):Promise<UnifiedWorkItem[]>{
  const items:UnifiedWorkItem[]=[];const now=Date.now(),todayStart=startOfToday(),todayEnd=endOfToday();
  const feedback=await supabaseAdmin.from("sales_management_feedback").select("id,lead_id,handoff_id,feedback_type,message,created_at").eq("organisation_id",context.organisationId).eq("employee_id",context.employeeId).is("resolved_at",null).order("created_at",{ascending:false});
  for(const item of feedback.data||[])items.push({id:`manager-feedback:${item.id}`,sourceType:item.feedback_type==="handoff"?"handoff":"qualification",sourceId:item.handoff_id||item.lead_id||item.id,category:"Manager feedback",title:item.feedback_type==="handoff"?"Handoff needs clarification":"Qualification needs clarification",description:item.message,entityName:"Manager review",dueAt:null,priority:"high",status:"open",actionType:"resolve_feedback",href:item.lead_id?`/workspace/sales/leads/${item.lead_id}`:"/workspace/sales",createdAt:item.created_at,metadataSafe:{feedbackId:item.id},rank:4});
  const onboarding=await supabaseAdmin.schema("onboarding").from("employee_states").select("id,checklist,created_at").eq("organisation_id",context.organisationId).eq("employee_id",context.employeeId).maybeSingle();
  if(Array.isArray(onboarding.data?.checklist))for(const task of onboarding.data.checklist as any[])if(task.status!=="completed")items.push({id:`onboarding:${task.key}`,sourceType:"onboarding",sourceId:onboarding.data.id,category:"Onboarding",title:String(task.title),description:"Complete your employee onboarding action.",entityName:"GrowXLabs",dueAt:null,priority:"medium",status:"open",actionType:"open",href:"/workspace/employment",createdAt:onboarding.data.created_at,metadataSafe:{},rank:10});
  if(context.permissions.includes("sales.workspace")){
    const leads=await getAssignedLeads(context),leadIds=leads.map(l=>l.id),leadById=new Map(leads.map(l=>[l.id,l]));
    if(leadIds.length){
      const [activities,qualifications,opportunities,followups]=await Promise.all([
        supabaseAdmin.from("sales_activities").select("id,lead_id,occurred_at").eq("organisation_id",context.organisationId).eq("employee_id",context.employeeId).in("lead_id",leadIds),
        supabaseAdmin.from("lead_qualifications").select("*").eq("organisation_id",context.organisationId).eq("employee_id",context.employeeId).in("lead_id",leadIds),
        supabaseAdmin.from("sales_opportunities").select("id,originating_lead_id,name,stage,created_at").eq("organisation_id",context.organisationId).eq("owner_employee_id",context.employeeId).in("originating_lead_id",leadIds),
        supabaseAdmin.from("sales_followups").select("id,lead_id,context,due_at,priority,status,created_at,completed_at").eq("organisation_id",context.organisationId).eq("assigned_employee_id",context.employeeId).order("due_at").limit(200),
      ]);
      const activityLeadIds=new Set((activities.data||[]).map(a=>a.lead_id));
      for(const lead of leads)if(!activityLeadIds.has(lead.id)){const fresh=now-Date.parse(lead.assigned_at||lead.created_at)<86400000;items.push({id:`assigned:${lead.id}`,sourceType:"assigned_lead",sourceId:lead.id,category:"Prospect",title:fresh?"Review newly assigned prospect":"Prospect awaiting first action",description:fresh?"Review the prospect and begin research.":"No meaningful activity has been recorded since assignment.",entityName:lead.business_name||lead.name||"Prospect",dueAt:lead.assigned_at||lead.created_at,priority:fresh?"high":"urgent",status:"open",actionType:"open_lead",href:`/workspace/sales/leads/${lead.id}`,createdAt:lead.assigned_at||lead.created_at,metadataSafe:{phone:lead.phone||null,email:lead.email||null},rank:5});}
      for(const q of qualifications.data||[])if(q.state==="qualifying"){const missing:string[]=[];if(!q.problem_summary)missing.push("Problem");if(!q.stakeholders)missing.push("Decision context");if(!q.next_step)missing.push("Next step");if(missing.length){const lead=leadById.get(q.lead_id);items.push({id:`qualification:${q.lead_id}`,sourceType:"qualification",sourceId:q.lead_id,category:"Qualification",title:"Complete qualification",description:`Missing: ${missing.join(", ")}`,entityName:lead?.business_name||"Prospect",dueAt:null,priority:"high",status:"open",actionType:"continue_qualification",href:`/workspace/sales/leads/${q.lead_id}`,createdAt:q.updated_at||q.created_at,metadataSafe:{missing},rank:6})}}
      const opportunityIds=(opportunities.data||[]).map(o=>o.id);
      const [meetings,handoffs]=opportunityIds.length?await Promise.all([supabaseAdmin.from("sales_discovery_schedules").select("*").eq("organisation_id",context.organisationId).in("opportunity_id",opportunityIds),supabaseAdmin.from("sales_handoffs").select("id,opportunity_id,handed_off_at").eq("organisation_id",context.organisationId).in("opportunity_id",opportunityIds)]):[{data:[]},{data:[]}];
      const meetingByOpportunity=new Map((meetings.data||[]).map(m=>[m.opportunity_id,m])),handoffIds=new Set((handoffs.data||[]).map(h=>h.opportunity_id));
      for(const o of opportunities.data||[]){const lead=leadById.get(o.originating_lead_id),meeting=meetingByOpportunity.get(o.id);if(o.stage==="qualified"&&!meeting)items.push({id:`discovery-schedule:${o.id}`,sourceType:"discovery_meeting",sourceId:o.id,category:"Discovery",title:"Schedule discovery",description:"This qualified opportunity is ready for a GrowXLabs team conversation.",entityName:lead?.business_name||o.name,dueAt:null,priority:"high",status:"open",actionType:"schedule_discovery",href:`/workspace/sales/opportunities/${o.id}`,createdAt:o.created_at,metadataSafe:{},rank:7});if(meeting&&meeting.status==="scheduled"){const start=Date.parse(meeting.scheduled_start),soon=start-now<=48*3600000;if(!meeting.prepared_at&&soon)items.push({id:`meeting-prep:${meeting.id}`,sourceType:"discovery_meeting",sourceId:meeting.id,category:"Meeting",title:"Prepare for discovery",description:meeting.qualification_summary,entityName:lead?.business_name||o.name,dueAt:meeting.scheduled_start,priority:start-now<=2*3600000?"urgent":"high",status:"open",actionType:"prepare_meeting",href:`/workspace/sales/meetings?meeting=${meeting.id}`,createdAt:meeting.created_at,metadataSafe:{opportunityId:o.id,internalEmployeeIds:meeting.internal_employee_ids},rank:start-now<=2*3600000?3:4});else if(start>=now)items.push({id:`meeting:${meeting.id}`,sourceType:"discovery_meeting",sourceId:meeting.id,category:"Meeting",title:"Upcoming discovery meeting",description:meeting.agenda_context,entityName:lead?.business_name||o.name,dueAt:meeting.scheduled_start,priority:start-now<=2*3600000?"urgent":"medium",status:"open",actionType:"open_meeting",href:`/workspace/sales/meetings?meeting=${meeting.id}`,createdAt:meeting.created_at,metadataSafe:{meetingUrl:meeting.meeting_url||null},rank:3});if(!handoffIds.has(o.id))items.push({id:`handoff:${o.id}`,sourceType:"handoff",sourceId:o.id,category:"Handoff",title:"Complete internal handoff",description:"Review the discovery brief and hand this opportunity to the GrowXLabs team.",entityName:lead?.business_name||o.name,dueAt:meeting.scheduled_start,priority:"high",status:"open",actionType:"complete_handoff",href:`/workspace/sales/opportunities/${o.id}`,createdAt:meeting.created_at,metadataSafe:{meetingId:meeting.id},rank:8})}if(meeting?.status==="completed"&&(meeting.attended_by_employee_ids||[]).includes(context.employeeId)&&!meeting.key_points)items.push({id:`meeting-notes:${meeting.id}`,sourceType:"discovery_meeting",sourceId:meeting.id,category:"Meeting",title:"Complete meeting notes",description:"Record the outcome, key points and next step.",entityName:lead?.business_name||o.name,dueAt:meeting.completed_at,priority:"high",status:"open",actionType:"meeting_notes",href:`/workspace/sales/meetings?meeting=${meeting.id}`,createdAt:meeting.completed_at||meeting.created_at,metadataSafe:{},rank:4})}
      for(const f of followups.data||[]){const lead=leadById.get(f.lead_id),due=Date.parse(f.due_at);if(f.status==="completed"&&Date.parse(f.completed_at||"")>=todayStart)items.push({id:`followup:${f.id}`,sourceType:"crm_followup",sourceId:f.id,category:"Follow-up",title:"Follow-up completed",description:f.context,entityName:lead?.business_name||"Prospect",dueAt:f.due_at,priority:f.priority,status:"completed",actionType:"open",href:`/workspace/sales/leads/${f.lead_id}`,createdAt:f.created_at,metadataSafe:{leadId:f.lead_id},rank:20});else if(f.status==="open")items.push({id:`followup:${f.id}`,sourceType:"crm_followup",sourceId:f.id,category:"Follow-up",title:"Follow up",description:f.context,entityName:lead?.business_name||"Prospect",dueAt:f.due_at,priority:due<now?"urgent":f.priority,status:"open",actionType:"complete_followup",href:`/workspace/sales/leads/${f.lead_id}`,createdAt:f.created_at,metadataSafe:{leadId:f.lead_id,phone:lead?.phone||null,email:lead?.email||null},rank:due<now?1:due<=todayEnd?2:9})}
    }
  }
  const filtered=items.filter(item=>{const due=item.dueAt?Date.parse(item.dueAt):null;if(view==="all")return true;if(view==="completed")return item.status==="completed";if(item.status==="completed")return false;if(view==="overdue")return due!==null&&due<now;if(view==="upcoming")return due!==null&&due>todayEnd;return due===null||due<=todayEnd});
  return filtered.sort((a,b)=>a.rank-b.rank||(Date.parse(a.dueAt||"9999-12-31")-Date.parse(b.dueAt||"9999-12-31"))).slice(0,200);
}
