"use client";

import { useQuery } from "@tanstack/react-query";

type Project = { project_number: string; status: string; activated_at: string | null; project_workspaces: Array<{ status: string; health: string; summary: Record<string, unknown>; project_milestones: Array<{ milestone_number: string; name: string; status: string; planned_completion: string | null; progress: number }>; project_tasks: Array<{ task_number: string; title: string; status: string; priority: string; due_date: string | null }>; project_deliverables: Array<{ deliverable_number: string; title: string; status: string; version: number; client_review_status: string }>; project_releases: Array<{ release_number: string; version: string; environment: string; status: string; release_notes: string | null; deployed_at: string | null }> }>; };

async function loadProjects() { const response = await fetch("/api/client/consulting-projects", { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Unable to load projects."); return body as { projects: Project[] }; }
const display = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());

export default function ClientProjectPage() { const query = useQuery({ queryKey: ["client", "projects"], queryFn: loadProjects }); if (query.isPending) return <p>Loading project workspace…</p>; if (query.error) return <p role="alert" className="text-red-700">{query.error.message}</p>; return <div className="space-y-6"><header><p className="text-xs font-bold uppercase tracking-[0.2em] text-slate-500">Delivery workspace</p><h1 className="mt-2 text-3xl font-bold">Projects</h1><p className="mt-2 text-slate-600">Track milestones, tasks, deliverables, approvals and releases.</p></header>{!query.data.projects.length && <section className="rounded-lg border border-slate-200 bg-white p-8"><h2 className="text-xl font-semibold">No active project yet</h2><p className="mt-2 text-slate-600">A project workspace will appear after agreement and payment activation.</p></section>}{query.data.projects.map((project) => <ProjectCard key={project.project_number} project={project} />)}</div>; }

function ProjectCard({ project }: { project: Project }) { const workspace = project.project_workspaces[0]; return <section className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-500">{project.project_number}</p><h2 className="mt-2 text-2xl font-semibold">Project Workspace</h2></div><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-800">{display(workspace?.status || project.status)}</span></div>{workspace ? <div className="mt-6 grid gap-6 lg:grid-cols-2"><Panel title="Milestones">{workspace.project_milestones.length ? workspace.project_milestones.map((item) => <Row key={item.milestone_number} title={item.name} meta={`${item.progress}% · ${display(item.status)}`} />) : <Empty />}</Panel><Panel title="Client-visible tasks">{workspace.project_tasks.length ? workspace.project_tasks.map((item) => <Row key={item.task_number} title={item.title} meta={display(item.status)} />) : <Empty />}</Panel><Panel title="Deliverables">{workspace.project_deliverables.length ? workspace.project_deliverables.map((item) => <Row key={item.deliverable_number} title={item.title} meta={`Version ${item.version} · ${display(item.client_review_status)}`} />) : <Empty />}</Panel><Panel title="Releases">{workspace.project_releases.length ? workspace.project_releases.map((item) => <Row key={item.release_number} title={`${item.release_number} · ${item.version}`} meta={`${display(item.environment)} · ${display(item.status)}`} />) : <Empty />}</Panel></div> : <p className="mt-6 rounded bg-slate-50 p-4 text-sm text-slate-600">Project activation is complete; the delivery workspace is being prepared.</p>}</section>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <div className="rounded-lg border border-slate-200 p-4"><h3 className="font-semibold">{title}</h3><div className="mt-3 divide-y divide-slate-100">{children}</div></div>; }
function Row({ title, meta }: { title: string; meta: string }) { return <div className="flex items-center justify-between gap-4 py-3 text-sm"><span className="font-medium">{title}</span><span className="text-right text-slate-500">{meta}</span></div>; }
function Empty() { return <p className="py-3 text-sm text-slate-500">Nothing published yet.</p>; }
