"use client";
import { useEffect, useState } from "react";

type Project = { id?: string; project_number: string; status: string };
type Change = { id: string; change_number?: string; title: string; status: string; impact?: unknown; created_at: string };
const changeStatusLabels: Record<string, string> = { submitted: "Submitted", under_review: "Under review", approved: "Approved", rejected: "Declined", changes_required: "More information needed", completed: "Completed" };
const changeStatus = (value: string) => changeStatusLabels[value] || value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());

export default function ChangeRequestsPage() {
  const [projects, setProjects] = useState<Project[]>([]), [changes, setChanges] = useState<Change[]>([]);
  const [projectId, setProjectId] = useState(""), [title, setTitle] = useState(""), [description, setDescription] = useState(""), [impact, setImpact] = useState(""), [busy, setBusy] = useState(false), [message, setMessage] = useState("");
  useEffect(() => { fetch("/api/client/consulting-projects", { cache: "no-store" }).then(r => r.json()).then(b => { const rows = b.projects || []; setProjects(rows); if (rows[0]) setProjectId(rows[0].id || rows[0].project_number); }).catch(() => setMessage("Unable to load projects.")); }, []);
  useEffect(() => { if (!projectId) return; fetch(`/api/client/delivery/change-requests?projectId=${encodeURIComponent(projectId)}`, { cache: "no-store" }).then(r => r.json()).then(b => setChanges(b.changes || [])).catch(() => setChanges([])); }, [projectId]);
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setMessage(""); try { const response = await fetch("/api/client/delivery/change-requests", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ projectId, title, description, impact }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Unable to submit request."); setChanges(current => [{ ...body.changeRequest, created_at: body.changeRequest.created_at }, ...current]); setTitle(""); setDescription(""); setImpact(""); setMessage("Change request submitted successfully."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to submit request."); } finally { setBusy(false); } }
  return <div className="space-y-8"><header><p className="text-xs font-bold uppercase tracking-[0.2em] text-slate-500">Project delivery</p><h1 className="mt-2 text-3xl font-bold">Change Requests</h1><p className="mt-2 text-slate-600">Request a scope, requirement, timeline, or deliverable change from the delivery team.</p></header><section className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Submit a request</h2><form onSubmit={submit} className="mt-5 space-y-4"><label className="block text-sm font-semibold">Project<select required value={projectId} onChange={e => setProjectId(e.target.value)} className="mt-2 h-11 w-full rounded-lg border border-slate-300 px-3">{projects.length ? projects.map(p => <option key={p.id || p.project_number} value={p.id || p.project_number}>{p.project_number}</option>) : <option value="">No active projects</option>}</select></label><label className="block text-sm font-semibold">Title<input required value={title} onChange={e => setTitle(e.target.value)} placeholder="Describe the requested change" className="mt-2 h-11 w-full rounded-lg border border-slate-300 px-3" /></label><label className="block text-sm font-semibold">Description<textarea required value={description} onChange={e => setDescription(e.target.value)} rows={5} placeholder="What should change and why?" className="mt-2 w-full rounded-lg border border-slate-300 p-3" /></label><label className="block text-sm font-semibold">Expected impact<textarea value={impact} onChange={e => setImpact(e.target.value)} rows={3} placeholder="Timing, budget, dependencies (optional)" className="mt-2 w-full rounded-lg border border-slate-300 p-3" /></label>{message && <p className="rounded-lg bg-slate-50 p-3 text-sm text-slate-700">{message}</p>}<button disabled={busy || !projectId} className="rounded-lg bg-[#0075de] px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{busy ? "Submitting…" : "Submit change request"}</button></form></section><section className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Request history</h2><div className="mt-4 divide-y divide-slate-100">{changes.length ? changes.map(item => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 py-4"><div><p className="font-semibold">{item.change_number || "Request"} · {item.title}</p><p className="text-sm text-slate-500">{new Date(item.created_at).toLocaleString()}</p></div><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700">{changeStatus(item.status)}</span></div>) : <p className="py-6 text-sm text-slate-500">No requests for this project yet.</p>}</div></section></div>;
}
