"use client";
import { useQuery } from "@tanstack/react-query";
import { DocumentContainer,DocumentShell } from "@/components/document/DocumentShell";
import { AiSolutionReportDocument } from "@/components/consulting/AiSolutionReportDocument";
import { consultingStatusLabel } from "@/lib/consulting/status";
const labels:Record<string,string>={business_capabilities:"Business Capabilities",architecture_overview:"Architecture Overview",components:"Core Components",data_architecture:"Data Architecture",integrations:"Integration Architecture",workflows:"Workflow Design",ai_components:"AI Components",security_controls:"Security & Governance",implementation_phases:"Implementation Phases",risks:"Risks & Assumptions",decisions:"Architecture Decisions",traceability:"Requirements Traceability"};
export function ClientDocument({kind,id}:{kind:"report"|"architecture";id:string}){
 const config=kind==="report"?{endpoint:"/api/client/ai-solution-reports",root:"report",number:"report_number",title:"AI Opportunity & Solution Report"}:{endpoint:"/api/client/solution-architectures",root:"architecture",number:"architecture_number",title:"Solution Architecture Document"};
 const query=useQuery<{[key:string]:Record<string,unknown>}>({queryKey:["client",kind,id],queryFn:async()=>{const r=await fetch(`${config.endpoint}/${id}`),b=await r.json();if(!r.ok)throw new Error(b.error||"Document unavailable.");return b;}});
 if(query.isPending)return <p className="p-8">Loading document…</p>;if(query.error)return <p className="p-8 text-red-700">{query.error.message}</p>;const doc=query.data[config.root];
 if(kind==="report")return <DocumentShell><DocumentContainer className="py-8 md:py-12"><AiSolutionReportDocument report={doc}/></DocumentContainer></DocumentShell>;
 const sections=Object.entries(doc).filter(([key,value])=>labels[key]&&value!==null);
 return <DocumentShell><DocumentContainer className="py-8 md:py-12"><article className="overflow-hidden border border-slate-300 bg-white shadow-sm print:border-0 print:shadow-none"><header className="border-b-2 border-slate-800 px-6 py-8 md:px-12 md:py-11"><div className="flex justify-between gap-6"><div><div className="text-2xl font-extrabold">GrowX<span className="text-[#1d5f8d]">Labs.tech</span></div><p className="mt-1 text-[10px] font-bold uppercase tracking-[.16em] text-slate-500">AI-Native Software Company</p></div><p className="text-right text-[11px] font-bold uppercase tracking-[.15em] text-red-800">Confidential</p></div><h1 className="mt-9 font-serif text-3xl md:text-4xl">{config.title}</h1><dl className="mt-8 grid gap-4 border-t pt-6 text-sm sm:grid-cols-2"><Meta label="Document Number" value={String(doc[config.number])}/><Meta label="Prepared By" value="GrowXLabs"/><Meta label="Document Status" value={consultingStatusLabel(String(doc.status))}/></dl></header><div className="px-6 md:px-12">{sections.map(([key,value],index)=><section key={key} className="border-b py-8"><h2 className="font-serif text-2xl"><span className="mr-3 text-[#1d4f7a]">{String(index+1).padStart(2,"0")}</span>{labels[key]}</h2><pre className="mt-4 whitespace-pre-wrap font-sans text-sm leading-6">{JSON.stringify(value,null,2)}</pre></section>)}</div></article></DocumentContainer></DocumentShell>
}
function Meta({label,value}:{label:string;value:string}){return <div><dt className="text-[10px] font-bold uppercase text-slate-500">{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>}
