import "server-only";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/auth";
import { supabaseAdmin } from "@/lib/supabase/admin";

export const CONSULTING_STATUSES = ["draft","internal_review","changes_required","approved_internal","ready_for_client","shared","client_reviewed","client_acknowledged","closed","archived"] as const;
export type ConsultingStatus = typeof CONSULTING_STATUSES[number];
export const statusLabel = (status: string) => ({draft:"Draft",internal_review:"Internal Review",changes_required:"Changes Required",approved_internal:"Internally Approved",ready_for_client:"Ready to Share",shared:"Shared with Client",client_reviewed:"Reviewed by Client",client_acknowledged:"Client Acknowledged",closed:"Complete",archived:"Archived",Draft:"Draft","Internal Review":"Internal Review","Ready for Client":"Ready to Share",Shared:"Shared with Client","Client Reviewed":"Reviewed by Client",Closed:"Complete"})[status] ?? status;
export class ConsultingHttpError extends Error { constructor(public status: number, message: string) { super(message); } }
export async function requireConsultingAdmin(){const session=await getServerSession(authOptions);if(!session?.user?.id)throw new ConsultingHttpError(401,"Authentication required.");if(!["ADMIN","CO_ADMIN"].includes(session.user.role))throw new ConsultingHttpError(403,"Consulting workspace permission is required.");return {userId:session.user.id};}
export async function requireConsultingClient(){const session=await getServerSession(authOptions);if(!session?.user?.id||session.user.role!=="CLIENT")throw new ConsultingHttpError(403,"A client account is required.");const {data,error}=await supabaseAdmin.from("client_profiles").select("id").eq("user_id",session.user.id).maybeSingle();if(error||!data)throw new ConsultingHttpError(403,"Client account is not linked.");return {userId:session.user.id,clientId:data.id};}
export function workflowError(error: unknown){return Response.json({error:error instanceof Error?error.message:"Consulting workflow request failed."},{status:error instanceof ConsultingHttpError?error.status:500});}
const unlockedAuditStatuses=["approved_internal","ready_for_client","shared","client_reviewed","client_acknowledged","closed","Ready for Client","Shared","Client Reviewed","Closed"];
const unlockedReportStatuses=["approved_internal","ready_for_client","shared","client_reviewed","client_acknowledged","closed"];
export async function createAiSolutionReport(auditId:string,userId:string){
  const {data:audit,error}=await supabaseAdmin.from("business_technical_audits").select("*").eq("id",auditId).maybeSingle();if(error)throw new Error(error.message);if(!audit)throw new ConsultingHttpError(404,"Audit not found.");if(!unlockedAuditStatuses.includes(audit.status))throw new ConsultingHttpError(409,"Approve the audit internally before creating the AI Opportunity & Solution Report.");
  const existing=await supabaseAdmin.from("ai_solution_reports").select("id,report_number").eq("audit_id",auditId).not("status","eq","archived").maybeSingle();if(existing.error)throw new Error(existing.error.message);if(existing.data)return existing.data;
  const payload={audit_id:audit.id,assessment_id:audit.assessment_id,discovery_meeting_id:audit.discovery_meeting_id,client_id:audit.client_id,company_id:audit.company_id,deal_id:audit.deal_id,created_by:userId,executive_summary:{content:"Draft — Requires Consultant Review",sourceAudit:audit.audit_number},business_outcomes:[],opportunity_map:[],opportunities:[],automation_opportunities:[],software_opportunities:[],solution_options:[],human_in_loop:[],data_requirements:[],integration_requirements:[],roadmap:[],risks:audit.risks||[],recommendations:[]};
  const {data,error:insertError}=await supabaseAdmin.from("ai_solution_reports").insert(payload).select("*").single();if(insertError)throw new Error(insertError.message);await recordActivity("ai_solution_report",data.id,userId,"admin","report_created",{auditNumber:audit.audit_number});return data;
}
export async function createSolutionArchitecture(reportId:string,userId:string){
  const {data:report,error}=await supabaseAdmin.from("ai_solution_reports").select("*").eq("id",reportId).maybeSingle();if(error)throw new Error(error.message);if(!report)throw new ConsultingHttpError(404,"AI Opportunity & Solution Report not found.");if(!unlockedReportStatuses.includes(report.status))throw new ConsultingHttpError(409,"Approve the AI Opportunity & Solution Report internally before creating the Solution Architecture.");
  const existing=await supabaseAdmin.from("solution_architectures").select("id,architecture_number").eq("ai_solution_report_id",reportId).not("status","eq","archived").maybeSingle();if(existing.error)throw new Error(existing.error.message);if(existing.data)return existing.data;
  const payload={ai_solution_report_id:report.id,audit_id:report.audit_id,assessment_id:report.assessment_id,discovery_meeting_id:report.discovery_meeting_id,client_id:report.client_id,company_id:report.company_id,deal_id:report.deal_id,created_by:userId,executive_summary:{content:"Draft — Requires Consultant Review",sourceReport:report.report_number},business_capabilities:[],architecture_overview:{},components:[],data_architecture:{},integrations:report.integration_requirements||[],workflows:[],ai_components:[],security_controls:[],implementation_phases:report.roadmap||[],risks:report.risks||[],decisions:[],traceability:[],diagram:{nodes:[],edges:[]}};
  const {data,error:insertError}=await supabaseAdmin.from("solution_architectures").insert(payload).select("*").single();if(insertError)throw new Error(insertError.message);await recordActivity("solution_architecture",data.id,userId,"admin","architecture_created",{reportNumber:report.report_number});return data;
}
export async function recordActivity(type:string,id:string,actorId:string|null,actorType:string,eventType:string,metadata:Record<string,unknown>={}){const {error}=await supabaseAdmin.from("consulting_document_activity").insert({document_type:type,document_id:id,actor_id:actorId,actor_type:actorType,event_type:eventType,metadata});if(error)throw new Error(error.message);}
