"use client";
import { FormEvent, useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";

export default function CandidateApplicationPage({ params }: { params: Promise<{ reference: string }> }) {
  const search = useSearchParams(); const [reference, setReference] = useState(""), [email, setEmail] = useState(search.get("email") || ""), [data, setData] = useState<any>(null), [error, setError] = useState(""), [loading, setLoading] = useState(false);
  void params.then(({ reference: routeReference }) => { if (!reference) setReference(routeReference); });
  useEffect(() => { if (!data) return; const timer = window.setInterval(() => { void fetch(`/api/v1/candidate/portal?reference=${encodeURIComponent(data.application.reference)}&email=${encodeURIComponent(data.candidate.email)}`, { cache: "no-store" }).then(r => r.ok ? r.json() : null).then(next => { if (next) setData(next); }); }, 30000); return () => window.clearInterval(timer); }, [data]);
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); const response = await fetch(`/api/v1/candidate/portal?reference=${encodeURIComponent(reference)}&email=${encodeURIComponent(email)}`, { cache: "no-store" }); const body = await response.json(); if (!response.ok) setError(body.error || "Unable to load application."); else setData(body); setLoading(false); }
  if (!data) return <main className="mx-auto max-w-md px-5 py-20"><h1 className="text-3xl font-black">Candidate Application Status</h1><p className="mt-2 text-sm text-slate-600">Enter the application reference and email used to apply.</p><form onSubmit={submit} className="mt-7 space-y-4"><input required value={reference} onChange={e => setReference(e.target.value)} placeholder="Application reference" className="h-12 w-full rounded-xl border px-3"/><input required type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="Email address" className="h-12 w-full rounded-xl border px-3"/>{error && <p className="text-sm text-red-600">{error}</p>}<button disabled={loading} className="h-12 w-full rounded-xl bg-[#0075de] font-bold text-white">{loading ? "Checking…" : "View application"}</button></form></main>;
  const stages = ["applied", "screening", "interview", "assessment", "offer", "hired"]; const current = stages.indexOf(String(data.application.stage).toLowerCase());
  return <main className="mx-auto max-w-4xl space-y-7 px-5 py-12"><header><p className="text-xs font-bold uppercase tracking-widest text-[#0075de]">Candidate portal</p><h1 className="mt-2 text-4xl font-black">Hello, {data.candidate.name}</h1><p className="mt-2 text-sm text-slate-600">{data.application.reference} · {data.application.jobTitle}</p></header><section className="rounded-2xl border bg-white p-6"><div className="grid gap-4 sm:grid-cols-4"><div><p className="text-xs text-slate-500">Applied</p><b>{new Date(data.application.appliedAt).toLocaleDateString()}</b></div><div><p className="text-xs text-slate-500">Current status</p><b>{data.application.stage}</b></div><div><p className="text-xs text-slate-500">Last updated</p><b>{new Date(data.application.updatedAt).toLocaleDateString()}</b></div></div><div className="mt-7 grid grid-cols-3 gap-2 sm:grid-cols-6">{stages.map((stage, index) => <div key={stage} className={`rounded-lg p-3 text-center text-xs font-bold ${index <= current ? "bg-[#0075de] text-white" : "bg-slate-100 text-slate-500"}`}>{stage}</div>)}</div></section><section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-bold">Application timeline</h2><div className="mt-3 space-y-3">{data.timeline.map((event: any, index: number) => <div key={`${event.created_at}-${index}`} className="flex justify-between border-b py-2 text-sm"><b>{String(event.to_stage || "update").replaceAll("_", " ")}</b><span className="text-slate-500">{new Date(event.created_at).toLocaleString()}</span></div>)}</div></section><section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-bold">Interviews</h2>{data.interviews.length ? data.interviews.map((interview: any) => <div key={interview.id} className="mt-4 rounded-xl bg-blue-50 p-4"><b>{new Date(interview.scheduled_at).toLocaleString()}</b><p className="mt-1 text-sm">Duration: {interview.duration_minutes} minutes</p>{interview.meeting_link && <a className="mt-3 inline-block rounded-lg bg-[#0075de] px-4 py-2 text-sm font-bold text-white" href={interview.meeting_link} target="_blank">Join interview</a>}</div>) : <p className="mt-3 text-sm text-slate-500">No interview scheduled yet.</p>}</section>{data.offer && <section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-bold">Offer</h2><p className="mt-2 text-sm">Status: {data.offer.status}</p></section>}<section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-bold">Messages from HR</h2>{data.messages.length ? data.messages.map((message: any) => <div key={message.id} className="border-b py-3"><b>{message.subject}</b><p className="text-xs text-slate-500">{message.status} · {new Date(message.sent_at || message.created_at).toLocaleString()}</p></div>) : <p className="mt-3 text-sm text-slate-500">No messages yet.</p>}</section></main>;
}
