"use client";
import { useState } from "react";
import Link from "next/link";

type Props = { job: Record<string, any> };
const steps = ["Profile", "Experience", "Resume", "Questions", "Review"];

export default function ApplyForm({ job }: Props) {
  const [step, setStep] = useState(0); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [result, setResult] = useState<any>(null); const [file, setFile] = useState("");
  const [data, setData] = useState<any>({ profile: { full_name: "", email: "", phone: "", city: "", linkedin_url: "" }, experience: { current_role: "", institution: "", years: "", availability: "" }, answers: {}, consent: false });
  const update = (section: string, key: string, value: string) => setData((d: any) => ({ ...d, [section]: { ...d[section], [key]: value } }));
  const questions = Array.isArray(job.application_questions) ? job.application_questions : [];
  const next = () => { setError(""); if (step === 0 && (!data.profile.full_name || !data.profile.email)) return setError("Name and email are required."); if (step === 2 && !file) return setError("Please upload a PDF, DOC or DOCX resume."); setStep((s) => Math.min(4, s + 1)); };
  async function submit() { setBusy(true); setError(""); try { const response = await fetch(`/api/v1/careers/jobs/${job.slug}/applications`, { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify({ candidate_id: data.profile.email, profile: data.profile, experience: data.experience, answers: data.answers, resume_path: file }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || body.code || "Unable to submit application"); setResult(body.application); } catch (e: any) { setError(e.message); } finally { setBusy(false); } }
  if (result) return <section className="border border-white/10 bg-white/[.03] p-7 sm:p-10"><p className="font-mono text-[10px] uppercase tracking-[.2em] text-[#c0f0fb]">Application submitted</p><h2 className="mt-4 text-3xl font-semibold">Thank you for applying.</h2><p className="mt-4 text-zinc-400">{job.title}</p><p className="mt-8 text-sm text-zinc-300">Application reference: <strong className="text-white">{result.application_reference}</strong></p><Link href="/careers" className="mt-8 inline-block border border-white/20 px-5 py-3 text-xs font-bold uppercase tracking-wider hover:border-white">Return to careers</Link></section>;
  return <section className="border border-white/10 bg-white/[.03] p-6 sm:p-10"><nav className="mb-10 flex flex-wrap gap-4 border-b border-white/10 pb-5 font-mono text-[10px] uppercase tracking-widest text-zinc-500">{steps.map((label, i) => <span key={label} className={i === step ? "text-[#c0f0fb]" : ""}>{String(i + 1).padStart(2, "0")} {label}</span>)}</nav>
    {step === 0 && <Fieldset title="Candidate profile"><Input label="Full name" value={data.profile.full_name} onChange={(v) => update("profile", "full_name", v)} /><Input label="Email" type="email" value={data.profile.email} onChange={(v) => update("profile", "email", v)} /><Input label="Phone number" value={data.profile.phone} onChange={(v) => update("profile", "phone", v)} /><Input label="Current city" value={data.profile.city} onChange={(v) => update("profile", "city", v)} /><Input label="LinkedIn URL (optional)" value={data.profile.linkedin_url} onChange={(v) => update("profile", "linkedin_url", v)} /></Fieldset>}
    {step === 1 && <Fieldset title="Experience"><Input label="Current role or status" value={data.experience.current_role} onChange={(v) => update("experience", "current_role", v)} /><Input label="Company or institution" value={data.experience.institution} onChange={(v) => update("experience", "institution", v)} /><Input label="Relevant experience" value={data.experience.years} onChange={(v) => update("experience", "years", v)} /><Input label="Availability to start" value={data.experience.availability} onChange={(v) => update("experience", "availability", v)} /></Fieldset>}
    {step === 2 && <Fieldset title="Resume"><label className="block cursor-pointer border border-dashed border-white/20 p-8 text-center text-sm text-zinc-400 hover:border-[#c0f0fb]"><input type="file" accept=".pdf,.doc,.docx" className="sr-only" onChange={async (e) => { const selected = e.target.files?.[0]; if (!selected || selected.size > 10 * 1024 * 1024) return setError("Resume must be PDF, DOC or DOCX up to 10 MB."); const fd = new FormData(); fd.append("file", selected); const r = await fetch("/api/careers/upload", { method: "POST", body: fd }); const b = await r.json(); if (!r.ok) return setError(b.error || "Upload failed"); setFile(b.path || b.url); }} />Choose resume · PDF, DOC or DOCX · max 10 MB</label>{file && <p className="mt-4 text-sm text-[#c0f0fb]">Resume uploaded securely.</p>}</Fieldset>}
    {step === 3 && <Fieldset title="Role questions">{questions.length ? questions.map((q: any, i: number) => { const key = q.id || q.key || String(i); return <label key={key} className="block text-sm text-zinc-300">{q.question || q.label}<textarea className="mt-2 min-h-24 w-full border border-white/15 bg-black/20 p-3 text-white outline-none focus:border-[#c0f0fb]" value={data.answers[key] || ""} onChange={(e) => setData((d: any) => ({ ...d, answers: { ...d.answers, [key]: e.target.value } }))} /></label>; }) : <p className="text-sm text-zinc-400">No additional questions for this role.</p>}</Fieldset>}
    {step === 4 && <Fieldset title="Review"><Review title="Profile" value={`${data.profile.full_name} · ${data.profile.email}`} /><Review title="Experience" value={data.experience.current_role || "Not provided"} /><Review title="Resume" value={file ? "Uploaded" : "Missing"} /><label className="mt-6 flex gap-3 text-sm text-zinc-300"><input type="checkbox" checked={data.consent} onChange={(e) => setData({ ...data, consent: e.target.checked })} /> I confirm this information is accurate and agree to the candidate privacy notice.</label></Fieldset>}
    {error && <p aria-live="polite" className="mt-6 border border-red-400/30 bg-red-400/5 p-3 text-sm text-red-300">{error}</p>}
    <div className="mt-10 flex justify-between"><button type="button" disabled={step === 0} onClick={() => setStep((s) => s - 1)} className="border border-white/15 px-5 py-3 text-xs font-bold uppercase tracking-wider disabled:opacity-30">Back</button>{step < 4 ? <button type="button" onClick={next} className="bg-[#c0f0fb] px-5 py-3 text-xs font-bold uppercase tracking-wider text-black">Continue</button> : <button type="button" disabled={busy || !data.consent} onClick={submit} className="bg-[#c0f0fb] px-5 py-3 text-xs font-bold uppercase tracking-wider text-black disabled:opacity-40">{busy ? "Submitting…" : "Submit application"}</button>}</div>
  </section>;
}
function Fieldset({ title, children }: { title: string; children: React.ReactNode }) { return <div><h2 className="text-2xl font-semibold">{title}</h2><div className="mt-7 space-y-5">{children}</div></div>; }
function Input({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (v: string) => void; type?: string }) { return <label className="block text-sm text-zinc-300">{label}<input type={type} value={value} onChange={(e) => onChange(e.target.value)} className="mt-2 w-full border border-white/15 bg-black/20 px-3 py-3 text-white outline-none focus:border-[#c0f0fb]" /></label>; }
function Review({ title, value }: { title: string; value: string }) { return <div className="border-b border-white/10 py-3"><span className="text-xs uppercase tracking-wider text-zinc-500">{title}</span><p className="mt-1 text-sm text-zinc-200">{value}</p></div>; }
