export type EditorialTheme = "light" | "dark";
export type EditorialAccess = "public" | "subscriber";

export interface EditorialRelatedPost {
  slug: string;
  title: string;
  category: string;
  date: string;
  image: string;
  alt: string;
}

export interface EditorialArticleData {
  slug: string;
  title: string;
  deck: string;
  category: string;
  tags: string[];
  author: string;
  publishedAt: string;
  updatedAt?: string;
  readTime: string;
  theme: EditorialTheme;
  heroImage: string;
  heroAlt: string;
  access: EditorialAccess;
  subscriptionGateAfter?: string;
  relatedPosts: EditorialRelatedPost[];
}

const sharedRelated: EditorialRelatedPost[] = [
  {
    slug: "chatbots-are-dying-agents-are-taking-over",
    title: "Chatbots Are Dying. Agents Are Taking Over.",
    category: "AI Systems",
    date: "June 1, 2026",
    image: "/images/blog-chatbots-agents-landscape.png",
    alt: "A conversation interface becoming an agent workflow",
  },
  {
    slug: "claude-opus-4-8-anthropic-ai-model",
    title: "Claude Opus 4.8: Anthropic’s Most Advanced AI Model",
    category: "AI Models",
    date: "May 29, 2026",
    image: "/images/blog-claude-opus-landscape.png",
    alt: "An editorial study of an AI research and coding system",
  },
  {
    slug: "why-anthropic-is-becoming-a-serious-threat-to-openai",
    title: "Why Anthropic Is Becoming a Serious Threat to OpenAI",
    category: "AI Industry",
    date: "May 27, 2026",
    image: "/images/hero-anthropic-openai.png",
    alt: "Anthropic and OpenAI represented in an editorial technology study",
  },
];

const articles: Record<string, EditorialArticleData> = {
  "ai-coding-tools-are-reshaping-modern-software-engineering": {
    slug: "ai-coding-tools-are-reshaping-modern-software-engineering",
    title: "AI Coding Tools Are Reshaping Modern Software Engineering",
    deck: "How AI coding systems are moving from autocomplete toward multi-step software work, faster iteration, and more strategic engineering decisions.",
    category: "Engineering",
    tags: ["AI tools", "Software engineering", "Developer workflows"],
    author: "GrowxLabs",
    publishedAt: "May 27, 2026",
    readTime: "5 min read",
    theme: "dark",
    heroImage: "/images/blog-ai-coding-landscape-v2.png",
    heroAlt: "A developer and coding agent collaborating across a structured software repository",
    access: "public",
    relatedPosts: sharedRelated,
  },
  "applied-intuition-dana-physical-ai-platform": {
    slug: "applied-intuition-dana-physical-ai-platform",
    title: "Dana: Applied Intuition’s Bold Bet on the Future of Physical AI",
    deck: "Applied Intuition’s Dana platform connects software intelligence with the vehicles, robots, and physical systems that have to act in the real world.",
    category: "Physical AI",
    tags: ["Robotics", "Applied Intuition", "Autonomy"],
    author: "GrowxLabs",
    publishedAt: "May 28, 2026",
    readTime: "6 min read",
    theme: "light",
    heroImage: "/images/blog-applied-intuition-dana.jpg",
    heroAlt: "Applied Intuition’s Dana physical AI platform",
    access: "public",
    relatedPosts: sharedRelated,
  },
  "blue-origin-new-glenn-rocket-explosion": {
    slug: "blue-origin-new-glenn-rocket-explosion",
    title: "Blue Origin’s New Glenn Rocket Explodes During Test: What Happened?",
    deck: "A hot-fire test failure at Blue Origin offers a close look at how launch teams learn from a difficult step in a long orbital program.",
    category: "Space Technology",
    tags: ["Blue Origin", "New Glenn", "Launch systems"],
    author: "GrowxLabs",
    publishedAt: "May 30, 2026",
    readTime: "5 min read",
    theme: "light",
    heroImage: "/images/blog-blue-origin-landscape.png",
    heroAlt: "Blue Origin’s New Glenn rocket during a test event",
    access: "public",
    relatedPosts: sharedRelated,
  },
  "chatbots-are-dying-agents-are-taking-over": {
    slug: "chatbots-are-dying-agents-are-taking-over",
    title: "Chatbots Are Dying. Agents Are Taking Over.",
    deck: "AI is moving from answering questions in a chat window to carrying out multi-step work across the systems businesses already use.",
    category: "AI Systems",
    tags: ["Agents", "Automation", "Business systems"],
    author: "GrowxLabs",
    publishedAt: "June 1, 2026",
    readTime: "7 min read",
    theme: "dark",
    heroImage: "/images/blog-chatbots-agents-landscape.png",
    heroAlt: "A conversation interface becoming an agent workflow",
    access: "public",
    relatedPosts: sharedRelated,
  },
  "chatgpt-gpt-5-6-preview-everything-you-need-to-know": {
    slug: "chatgpt-gpt-5-6-preview-everything-you-need-to-know",
    title: "ChatGPT GPT-5.6 Preview: Everything You Need to Know",
    deck: "A guide to OpenAI’s GPT-5.6 preview family, including its reasoning, coding, safety, benchmark, and agent workflow claims.",
    category: "AI Models",
    tags: ["OpenAI", "GPT-5.6", "Model research"],
    author: "GrowxLabs",
    publishedAt: "June 30, 2026",
    readTime: "8 min read",
    theme: "dark",
    heroImage: "/images/blog-chatgpt-gpt56-landscape.png",
    heroAlt: "An editorial study of the ChatGPT GPT-5.6 preview model family",
    access: "public",
    relatedPosts: sharedRelated,
  },
  "claude-fable-5-mythos-5-anthropic-models": {
    slug: "claude-fable-5-mythos-5-anthropic-models",
    title: "Claude Fable 5 & Mythos 5 Launch: Benchmarks & Guide",
    deck: "A practical guide to Anthropic’s Claude Fable 5 and Mythos 5 models, their benchmark positioning, use cases, and availability.",
    category: "AI Models",
    tags: ["Anthropic", "Claude", "Benchmarks"],
    author: "GrowxLabs",
    publishedAt: "May 31, 2026",
    readTime: "7 min read",
    theme: "dark",
    heroImage: "/images/blog-claude-fable-5-mythos-5.png",
    heroAlt: "An editorial study of Anthropic’s Claude Fable 5 and Mythos 5 models",
    access: "public",
    relatedPosts: sharedRelated,
  },
  "claude-fable-5-mythos-5-banned-us-government": {
    slug: "claude-fable-5-mythos-5-banned-us-government",
    title: "Claude Fable 5 & Mythos 5 Banned: Timeline & Impact",
    deck: "What the reported U.S. government restrictions around Anthropic’s models could mean for security, access, and companies building on them.",
    category: "AI Policy",
    tags: ["Anthropic", "AI policy", "Security"],
    author: "GrowxLabs",
    publishedAt: "June 2, 2026",
    readTime: "6 min read",
    theme: "dark",
    heroImage: "/images/blog-claude-fable-banned-landscape.png",
    heroAlt: "A secure research facility and restricted AI model artifact",
    access: "public",
    relatedPosts: sharedRelated,
  },
  "claude-opus-4-8-anthropic-ai-model": {
    slug: "claude-opus-4-8-anthropic-ai-model",
    title: "Claude Opus 4.8: Anthropic’s Most Advanced AI Model — Benchmarks, Features & Full Review",
    deck: "A detailed look at Claude Opus 4.8, including coding benchmarks, dynamic workflows, effort control, pricing, and API access.",
    category: "AI Models",
    tags: ["Anthropic", "Claude Opus", "Developer tools"],
    author: "GrowxLabs",
    publishedAt: "May 29, 2026",
    readTime: "8 min read",
    theme: "dark",
    heroImage: "/images/blog-claude-opus-landscape.png",
    heroAlt: "A research instrument, coding workspace, and server room representing Claude Opus 4.8",
    access: "public",
    relatedPosts: sharedRelated,
  },
  "cursor-origin-github-ai-code-hosting": {
    slug: "cursor-origin-github-ai-code-hosting",
    title: "Cursor Launches Origin: Why Cursor Is Moving Into GitHub’s Territory",
    deck: "Cursor is bringing repository hosting, pull requests, GitHub sync, and AI coding tools into the same workspace.",
    category: "Developer Tools",
    tags: ["Cursor", "GitHub", "AI coding"],
    author: "GrowxLabs",
    publishedAt: "August 17, 2026",
    updatedAt: "August 21, 2026",
    readTime: "8 min read",
    theme: "light",
    heroImage: "/images/blog-cursor-origin-landscape.png",
    heroAlt: "Cursor Origin connecting an AI editor with repositories and GitHub workflows",
    access: "public",
    relatedPosts: sharedRelated,
  },
  "elon-musks-path-to-becoming-the-worlds-first-trillionaire": {
    slug: "elon-musks-path-to-becoming-the-worlds-first-trillionaire",
    title: "Elon Musk’s Path to Becoming the World’s First Trillionaire: The Blueprint Behind the Empire",
    deck: "A data-led look at the companies, valuation logic, and execution risks behind Elon Musk’s path toward a trillion-dollar fortune.",
    category: "Business & Technology",
    tags: ["Tesla", "SpaceX", "AI industry"],
    author: "GrowxLabs",
    publishedAt: "June 3, 2026",
    readTime: "8 min read",
    theme: "light",
    heroImage: "/images/blog-elon-trillionaire-landscape.png",
    heroAlt: "Electric vehicles, aerospace, and AI systems connected in an editorial study",
    access: "public",
    relatedPosts: sharedRelated,
  },
  "ferraris-electric-future-why-the-luce-marks-a-historic-turning-point": {
    slug: "ferraris-electric-future-why-the-luce-marks-a-historic-turning-point",
    title: "Ferrari’s Electric Future: Why The Luce Marks A Historic Turning Point",
    deck: "Ferrari’s Luce signals how a heritage performance company can move toward electrification without giving up the physical character that made it distinctive.",
    category: "Mobility",
    tags: ["Ferrari", "Electric vehicles", "Design"],
    author: "GrowxLabs",
    publishedAt: "June 4, 2026",
    readTime: "7 min read",
    theme: "light",
    heroImage: "/images/blog-ferrari-luce-landscape.png",
    heroAlt: "Ferrari Luce between archival engine studies and an electric drivetrain",
    access: "public",
    relatedPosts: sharedRelated,
  },
  "google-io-2026": {
    slug: "google-io-2026",
    title: "Google I/O 2026: Gemini Spark, AI Agents & The Future of AI-Native Development",
    deck: "The major announcements from Google I/O 2026, from Gemini Spark and multimodal systems to the tools shaping AI-native software development.",
    category: "AI Infrastructure",
    tags: ["Google", "Gemini", "AI development"],
    author: "GrowxLabs",
    publishedAt: "May 27, 2026",
    readTime: "6 min read",
    theme: "dark",
    heroImage: "/images/blog-google-io-2026.png",
    heroAlt: "Google I/O 2026 and the next generation of Gemini development tools",
    access: "public",
    relatedPosts: sharedRelated,
  },
  "google-search-is-no-longer-just-search": {
    slug: "google-search-is-no-longer-just-search",
    title: "Google Search Is No Longer Just Search: The Rise of the Execution Engine",
    deck: "Google Search is moving from a list of links toward an AI-native workspace that can interpret information and help complete tasks.",
    category: "Search & AI",
    tags: ["Google Search", "Gemini", "AEO"],
    author: "GrowxLabs",
    publishedAt: "May 27, 2026",
    readTime: "5 min read",
    theme: "light",
    heroImage: "/images/hero-google-search.png",
    heroAlt: "An editorial study of Google Search becoming an execution engine",
    access: "public",
    relatedPosts: sharedRelated,
  },
  "kimi-k3-open-frontier-intelligence-model": {
    slug: "kimi-k3-open-frontier-intelligence-model",
    title: "Kimi K3 Technical Analysis: Inside Moonshot AI’s Open Frontier Intelligence Model",
    deck: "A technical look at Moonshot AI’s Kimi K3, including its mixture-of-experts design, sparse routing, and long-horizon benchmark performance.",
    category: "AI Models",
    tags: ["Kimi K3", "Moonshot AI", "Open models"],
    author: "GrowxLabs",
    publishedAt: "May 27, 2026",
    readTime: "9 min read",
    theme: "dark",
    heroImage: "/images/blog-kimi-k3-woodcut.png",
    heroAlt: "A technical editorial study of Moonshot AI’s Kimi K3 model",
    access: "public",
    relatedPosts: sharedRelated,
  },
  "nvidia-vision-agentic-to-useful-ai": {
    slug: "nvidia-vision-agentic-to-useful-ai",
    title: "NVIDIA’s Vision for the Future of AI: From Agentic AI to Useful AI",
    deck: "Jensen Huang’s GTC vision connects AI factories, CUDA-X, physical AI, and the shift from reactive chatbots to systems that execute work.",
    category: "AI Infrastructure",
    tags: ["NVIDIA", "Physical AI", "AI infrastructure"],
    author: "GrowxLabs",
    publishedAt: "May 27, 2026",
    readTime: "8 min read",
    theme: "dark",
    heroImage: "/images/nvidia-vision-agentic-to-useful-ai.png",
    heroAlt: "NVIDIA’s vision for useful AI and physical systems",
    access: "public",
    relatedPosts: sharedRelated,
  },
  "openai-huggingface-security-incident": {
    slug: "openai-huggingface-security-incident",
    title: "OpenAI × Hugging Face: The AI Security Incident That Changed Everything",
    deck: "A technical analysis of the reported ExploitGym incident and the security questions raised when frontier models operate across real infrastructure.",
    category: "AI Security",
    tags: ["OpenAI", "Hugging Face", "Security"],
    author: "GrowxLabs",
    publishedAt: "May 27, 2026",
    readTime: "8 min read",
    theme: "dark",
    heroImage: "/images/blog-openai-huggingface-incident.png",
    heroAlt: "An editorial study of AI model security and an exposed software infrastructure",
    access: "public",
    relatedPosts: sharedRelated,
  },
  "skyroot-aerospace-vikram-1-orbital-launch": {
    slug: "skyroot-aerospace-vikram-1-orbital-launch",
    title: "Skyroot Aerospace Launches Vikram-1, Ushering India Into Private Orbital Era",
    deck: "Skyroot’s Vikram-1 launch marks a significant moment for India’s private space sector and the engineering teams building a domestic orbital capability.",
    category: "Space Technology",
    tags: ["Skyroot", "Vikram-1", "India space"],
    author: "GrowxLabs",
    publishedAt: "May 27, 2026",
    readTime: "6 min read",
    theme: "light",
    heroImage: "/images/blog-skyroot-vikram1.png",
    heroAlt: "Skyroot Aerospace’s Vikram-1 launch and orbital mission",
    access: "public",
    relatedPosts: sharedRelated,
  },
  "stripe-openrouter-ai-infrastructure-acquisition": {
    slug: "stripe-openrouter-ai-infrastructure-acquisition",
    title: "Stripe Is Buying OpenRouter: Why a Payments Company Wants to Own Part of the AI Infrastructure Layer",
    deck: "Stripe’s reported OpenRouter acquisition shows how model routing, token usage, billing, and payments are converging into one infrastructure layer.",
    category: "AI Infrastructure",
    tags: ["Stripe", "OpenRouter", "Payments"],
    author: "GrowxLabs",
    publishedAt: "August 19, 2026",
    readTime: "8 min read",
    theme: "dark",
    heroImage: "/images/blog-stripe-openrouter-acquisition.png",
    heroAlt: "Payments and AI model routing represented as one infrastructure layer",
    access: "public",
    relatedPosts: sharedRelated,
  },
  "why-anthropic-is-becoming-a-serious-threat-to-openai": {
    slug: "why-anthropic-is-becoming-a-serious-threat-to-openai",
    title: "Why Anthropic Is Becoming a Serious Threat to OpenAI",
    deck: "Anthropic is challenging OpenAI through developer adoption, long-context systems, Claude Code, and a focused enterprise strategy.",
    category: "AI Industry",
    tags: ["Anthropic", "OpenAI", "AI industry"],
    author: "GrowxLabs",
    publishedAt: "May 27, 2026",
    readTime: "5 min read",
    theme: "light",
    heroImage: "/images/hero-anthropic-openai.png",
    heroAlt: "Anthropic and OpenAI represented in an editorial technology study",
    access: "public",
    relatedPosts: sharedRelated,
  },
};

export function getEditorialArticle(slug: string): EditorialArticleData | undefined {
  return articles[slug];
}

export function getEditorialArticleSlugs(): string[] {
  return Object.keys(articles);
}
