"use client";

import { FormEvent, useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { ColumnDef, flexRender, getCoreRowModel, useReactTable } from "@tanstack/react-table";
import { FileSignature, Plus, Send } from "lucide-react";

type Offer={id:string;applicationId:string;candidate:string;status:string;currentVersion:number;title:string;joiningDate:string;salaryAmount?:number;salaryCurrency?:string;expiresAt?:string};
async function api(path:string,init?:RequestInit){const response=await fetch(`/api/v1/hrms/onboarding${path}`,init);const body=response.status===204?null:await response.json();if(!response.ok)throw new Error(body?.detail||body?.error||"Request failed");return body}
export default function OfferWorkspace(){const client=useQueryClient(),[open,setOpen]=useState(false),[message,setMessage]=useState(""),[form,setForm]=useState({applicationID:"",title:"",joiningDate:"",departmentID:"",designationID:"",managerEmployeeID:"",employmentType:"full_time",workLocation:"",salaryAmount:"",salaryCurrency:"INR",probationDays:"90",noticePeriodDays:"30"});
const query=useQuery<{items:Offer[]}>({queryKey:["offers"],queryFn:()=>api("/offers")});async function action(path:string,body?:unknown){try{const result=await api(path,{method:"POST",headers:{"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});await client.invalidateQueries({queryKey:["offers"]});if(result?.publicPath)setMessage(`Candidate link: ${location.origin}${result.publicPath}`)}catch(error){setMessage(error instanceof Error?error.message:"Request failed")}}
async function create(event:FormEvent){event.preventDefault();await action("/offers",{applicationID:form.applicationID,expiresAt:new Date(Date.now()+7*86400000).toISOString(),version:{...form,salaryAmount:form.salaryAmount?Number(form.salaryAmount):null,probationDays:Number(form.probationDays),noticePeriodDays:Number(form.noticePeriodDays),benefits:[],terms:{}}});setOpen(false)}
const columns=useMemo<ColumnDef<Offer>[]>(()=>[{accessorKey:"candidate",header:"Candidate"},{accessorKey:"title",header:"Role"},{accessorKey:"joiningDate",header:"Joining"},{accessorKey:"salaryAmount",header:"Compensation",cell:({row})=>row.original.salaryAmount?`${row.original.salaryCurrency} ${row.original.salaryAmount.toLocaleString()}`:"—"},{accessorKey:"status",header:"Status"},{id:"actions",header:"Actions",cell:({row})=><div className="flex gap-2">{row.original.status==="draft"&&<button onClick={()=>void action(`/offers/${row.original.id}/submit`)} className="rounded border px-2 py-1 text-[9px] font-bold">Submit</button>}{row.original.status==="pending_approval"&&<button onClick={()=>void action(`/offers/${row.original.id}/approve`,{decision:"approved",comment:"Approved"})} className="rounded bg-emerald-600 px-2 py-1 text-[9px] font-bold text-white">Approve step</button>}{row.original.status==="approved"&&<button onClick={()=>void action(`/offers/${row.original.id}/send`)} className="flex items-center gap-1 rounded bg-[#0075de] px-2 py-1 text-[9px] font-bold text-white"><Send size={10}/>Send</button>}</div>}],[]);const table=useReactTable({data:query.data?.items||[],columns,getCoreRowModel:getCoreRowModel()});
return <div className="space-y-6"><header className="flex items-end justify-between border-b border-[var(--border-subtle)] pb-6"><div><div className="text-[10px] font-bold uppercase tracking-[.18em] text-[#0075de]">Release 03</div><h1 className="mt-2 text-3xl font-extrabold">Offer management</h1><p className="mt-2 text-xs text-[var(--text-secondary)]">Versioned employment offers with manager and HR approvals.</p></div><button onClick={()=>setOpen(true)} className="flex items-center gap-2 rounded-lg bg-[#0075de] px-4 py-2 text-xs font-bold text-white"><Plus size={14}/>Create offer</button></header>{message&&<p className="rounded-lg bg-blue-500/10 p-3 text-xs text-[#0075de]">{message}</p>}<div className="overflow-x-auto rounded-xl border border-[var(--border-subtle)] bg-[var(--card)]"><table className="w-full min-w-[850px] text-left text-xs"><thead className="bg-[var(--surface-2)]">{table.getHeaderGroups().map(group=><tr key={group.id}>{group.headers.map(header=><th key={header.id} className="px-4 py-3">{flexRender(header.column.columnDef.header,header.getContext())}</th>)}</tr>)}</thead><tbody>{table.getRowModel().rows.map(row=><tr key={row.id} className="border-t border-[var(--border-subtle)]">{row.getVisibleCells().map(cell=><td key={cell.id} className="px-4 py-3">{flexRender(cell.column.columnDef.cell,cell.getContext())}</td>)}</tr>)}</tbody></table>{!query.isLoading&&!query.data?.items?.length&&<div className="py-16 text-center text-xs text-[var(--text-muted)]"><FileSignature className="mx-auto mb-3"/>No offers yet.</div>}</div>{open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" onClick={()=>setOpen(false)}><form onSubmit={create} onClick={event=>event.stopPropagation()} className="grid max-h-[90vh] w-full max-w-2xl gap-3 overflow-y-auto rounded-2xl bg-[var(--background)] p-6 sm:grid-cols-2"><h2 className="sm:col-span-2 text-xl font-black">Create offer</h2>{Object.entries(form).map(([key,value])=><label key={key} className="text-[9px] font-bold uppercase text-[var(--text-muted)]">{key.replace(/[A-Z]/g,m=>` ${m}`).trim()}<input required={["applicationID","title","joiningDate"].includes(key)} type={key==="joiningDate"?"date":key.includes("Amount")||key.includes("Days")?"number":"text"} value={value} onChange={event=>setForm({...form,[key]:event.target.value})} className="mt-1 h-10 w-full rounded-lg border border-[var(--border-subtle)] bg-transparent px-3 text-xs normal-case"/></label>)}<button className="sm:col-span-2 rounded-lg bg-[#0075de] py-3 text-xs font-bold text-white">Save immutable version 1</button></form></div>}</div>}
