"use client";

import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, ChevronRight, CircleAlert, ClipboardCheck, Clock3, X } from "lucide-react";

type Instance={id:string;employee:string;employeeId:string;status:string;targetStartDate:string;total:number;completed:number;overdue:number};
type Task={id:string;key:string;title:string;description?:string;assigneeType:string;taskType:string;status:string;required:boolean;dueAt?:string;submittedData?:unknown};
type Detail={id:string;employeeId:string;status:string;targetStartDate:string;tasks:Task[];verifications:{id:string;documentType:string;status:string;notes?:string}[]};
async function api(path:string,init?:RequestInit){const response=await fetch(`/api/v1/hrms/onboarding${path}`,init);const body=response.status===204?null:await response.json();if(!response.ok)throw new Error(body?.detail||body?.error||"Request failed");return body}
export default function OnboardingWorkspace({scope,title}:{scope:""|"hr"|"manager"|"it";title:string}){const client=useQueryClient(),[selected,setSelected]=useState<Instance|null>(null);const query=useQuery<{items:Instance[]}>({queryKey:["onboarding-instances",scope],queryFn:()=>api(`/instances${scope?`?scope=${scope}`:""}`)});return <div className="space-y-6"><header className="border-b border-[var(--border-subtle)] pb-6"><div className="text-[10px] font-bold uppercase tracking-[.18em] text-[#0075de]">Release 03 · Onboarding</div><h1 className="mt-2 text-3xl font-extrabold">{title}</h1><p className="mt-2 text-xs text-[var(--text-secondary)]">Track dependencies, overdue work, document verification and onboarding completion.</p></header><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{query.isLoading?Array.from({length:6}).map((_,i)=><div key={i} className="h-40 animate-pulse rounded-xl bg-[var(--surface-2)]"/>):query.data?.items?.map(item=>{const progress=item.total?Math.round(item.completed/item.total*100):0;return <button key={item.id} onClick={()=>setSelected(item)} className="rounded-xl border border-[var(--border-subtle)] bg-[var(--card)] p-5 text-left"><div className="flex items-start justify-between"><div><b className="text-sm">{item.employee}</b><p className="mt-1 text-[10px] text-[var(--text-muted)]">Starts {new Date(item.targetStartDate).toLocaleDateString()}</p></div><ChevronRight size={16}/></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-[var(--surface-2)]"><div className="h-full bg-[#0075de]" style={{width:`${progress}%`}}/></div><div className="mt-2 flex justify-between text-[9px] font-bold"><span>{progress}% complete</span><span className={item.overdue?"text-red-500":"text-emerald-600"}>{item.overdue} overdue</span></div></button>})}</div>{!query.isLoading&&!query.data?.items?.length&&<div className="py-20 text-center text-xs text-[var(--text-muted)]"><ClipboardCheck className="mx-auto mb-3"/>No onboarding instances in this workspace.</div>}{selected&&<InstanceFlyout instance={selected} scope={scope} onClose={()=>setSelected(null)} onChanged={()=>client.invalidateQueries({queryKey:["onboarding-instances"]})}/>}</div>}
function InstanceFlyout({instance,scope,onClose,onChanged}:{instance:Instance;scope:string;onClose:()=>void;onChanged:()=>void}){const detail=useQuery<Detail>({queryKey:["onboarding-instance",instance.id],queryFn:()=>api(`/instances/${instance.id}`)});async function complete(task:Task,decision="completed"){await api(`/tasks/${task.id}/complete`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({decision})});await detail.refetch();onChanged()}async function verify(id:string,decision:string){await api(`/identity-verifications/${id}/decision`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({decision,notes:`${decision} by HR`})});await detail.refetch()}const visible=detail.data?.tasks?.filter(task=>!scope||task.assigneeType===scope)||[];return <div className="fixed inset-0 z-50 bg-black/30" onClick={onClose}><aside onClick={e=>e.stopPropagation()} className="absolute right-0 top-0 h-full w-full max-w-xl overflow-y-auto bg-[var(--background)] p-6 shadow-2xl"><div className="flex justify-between"><div><span className="text-[10px] font-bold uppercase text-[#0075de]">Onboarding checklist</span><h2 className="mt-2 text-xl font-black">{instance.employee}</h2></div><button onClick={onClose}><X/></button></div><div className="mt-6 space-y-3">{visible.map(task=><article key={task.id} className="rounded-xl border border-[var(--border-subtle)] p-4"><div className="flex gap-3">{task.status==="completed"?<CheckCircle2 className="text-emerald-600" size={18}/>:task.status==="blocked"?<CircleAlert className="text-amber-500" size={18}/>:<Clock3 className="text-[#0075de]" size={18}/>}<div className="flex-1"><b className="text-xs">{task.title}</b><p className="mt-1 text-[10px] text-[var(--text-muted)]">{task.description||task.taskType} · {task.status}</p></div>{!["completed","waived","blocked"].includes(task.status)&&<button onClick={()=>void complete(task)} className="rounded-lg bg-[#0075de] px-3 py-2 text-[9px] font-bold text-white">Complete</button>}</div></article>)}</div>{scope==="hr"&&detail.data?.verifications?.length?<section className="mt-7"><h3 className="text-xs font-black">Identity verification</h3><div className="mt-3 space-y-2">{detail.data.verifications.map(item=><div key={item.id} className="flex items-center rounded-lg border p-3 text-xs"><span className="flex-1">{item.documentType} · {item.status}</span>{item.status==="pending"&&<><button onClick={()=>void verify(item.id,"verified")} className="mr-2 text-emerald-600">Verify</button><button onClick={()=>void verify(item.id,"rejected")} className="text-red-600">Reject</button></>}</div>)}</div></section>:null}</aside></div>}
