import crypto from "node:crypto";

export type ProposalStatus="draft"|"internal_review"|"changes_required"|"approved_internal"|"ready_for_client"|"sent"|"viewed"|"request_changes"|"accepted"|"rejected"|"expired"|"cancelled"|"archived";
export type ProposalAction="request_internal_review"|"request_internal_changes"|"approve_internal"|"mark_ready_for_client"|"send"|"mark_viewed"|"mark_expired"|"cancel"|"archive"|"revise";
export type PricingLine={description:string;quantity:number;unit:string;unitPrice:number;discount:number};
export type PaymentMilestone={name:string;percentage:number;trigger:string;description?:string};
export type TaxInput={type:string;rate:number};
export const TRANSITIONS:Record<ProposalStatus,Partial<Record<ProposalAction,ProposalStatus>>>={draft:{request_internal_review:"internal_review",cancel:"cancelled"},internal_review:{request_internal_changes:"changes_required",approve_internal:"approved_internal",cancel:"cancelled"},changes_required:{revise:"draft",cancel:"cancelled"},approved_internal:{mark_ready_for_client:"ready_for_client",request_internal_changes:"changes_required",cancel:"cancelled"},ready_for_client:{send:"sent",request_internal_changes:"changes_required",cancel:"cancelled"},sent:{mark_viewed:"viewed",mark_expired:"expired"},viewed:{mark_expired:"expired"},request_changes:{revise:"draft"},accepted:{archive:"archived"},rejected:{archive:"archived"},expired:{archive:"archived"},cancelled:{archive:"archived"},archived:{}};
const money=(value:number)=>Math.round((value+Number.EPSILON)*100)/100;
export function calculateCommercials(lines:PricingLine[],tax:TaxInput,currency="INR"){if(!/^[A-Z]{3}$/.test(currency))throw new Error("Currency must be an ISO 4217 code.");if(!Array.isArray(lines)||!lines.length)throw new Error("At least one pricing line is required.");if(!tax||!Number.isFinite(tax.rate)||tax.rate<0||tax.rate>100)throw new Error("Tax rate must be between 0 and 100.");const normalized=lines.map((line,index)=>{const quantity=Number(line.quantity),unitPrice=money(Number(line.unitPrice)),discount=money(Number(line.discount||0));if(!String(line.description||"").trim())throw new Error(`Pricing line ${index+1} requires a description.`);if(!Number.isFinite(quantity)||quantity<=0)throw new Error(`Pricing line ${index+1} quantity must be greater than zero.`);if(!Number.isFinite(unitPrice)||unitPrice<0||!Number.isFinite(discount)||discount<0)throw new Error(`Pricing line ${index+1} contains an invalid amount.`);const gross=money(quantity*unitPrice);if(discount>gross)throw new Error(`Pricing line ${index+1} discount exceeds its gross amount.`);return{description:line.description.trim(),quantity,unit:String(line.unit||"item"),unit_price:unitPrice,discount,subtotal:money(gross-discount)}});const grossSubtotal=money(normalized.reduce((sum,line)=>sum+line.quantity*line.unit_price,0)),discount=money(normalized.reduce((sum,line)=>sum+line.discount,0)),taxableSubtotal=money(grossSubtotal-discount),taxAmount=money(taxableSubtotal*tax.rate/100),grandTotal=money(taxableSubtotal+taxAmount);return{lines:normalized,totals:{currency,subtotal:grossSubtotal,discount,taxable_subtotal:taxableSubtotal,tax_type:String(tax.type||"Tax"),tax_rate:tax.rate,tax_amount:taxAmount,grand_total:grandTotal}};}
export function validatePaymentMilestones(items:PaymentMilestone[]){if(!Array.isArray(items)||!items.length)throw new Error("At least one payment milestone is required.");const normalized=items.map((item,index)=>{const percentage=Number(item.percentage);if(!String(item.name||"").trim()||!String(item.trigger||"").trim())throw new Error(`Payment milestone ${index+1} requires a name and trigger.`);if(!Number.isFinite(percentage)||percentage<=0||percentage>100)throw new Error(`Payment milestone ${index+1} percentage is invalid.`);return{name:item.name.trim(),percentage,trigger:item.trigger.trim(),description:String(item.description||"").trim()}});const total=money(normalized.reduce((sum,item)=>sum+item.percentage,0));if(total!==100)throw new Error("Payment milestone percentages must total 100.");return normalized;}
export function transitionStatus(status:ProposalStatus,action:ProposalAction){const next=TRANSITIONS[status]?.[action];if(!next)throw new Error(`Invalid proposal transition: ${status} -> ${action}.`);return next;}
export function isExpired(validUntil:string|null|undefined,now=new Date()){return Boolean(validUntil)&&new Date(`${validUntil}T23:59:59.999Z`).getTime()<now.getTime();}
function stable(value:unknown):unknown{if(Array.isArray(value))return value.map(stable);if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>[key,stable(item)]));return value;}
export function proposalContentHash(snapshot:Record<string,unknown>){return crypto.createHash("sha256").update(JSON.stringify(stable(snapshot))).digest("hex");}
export function toClientProposalDto(proposal:Record<string,any>){return{id:proposal.id,proposalNumber:proposal.proposal_number,status:proposal.status,version:proposal.version,validUntil:proposal.valid_until,assessmentId:proposal.assessment_id,clientId:proposal.client_id,companyId:proposal.company_id,dealId:proposal.deal_id,clientContent:proposal.client_content||{},pricing:proposal.pricing||[],commercialTotals:proposal.commercial_totals||{},paymentSchedule:proposal.payment_schedule||[]};}
