import "server-only";
import { supabaseAdmin } from "@/lib/supabase/admin";
import { recordAuditEvent } from "@/lib/activity/events";
import { ConsultingHttpError } from "@/lib/consulting/workflow";
import { calculateCommercials,isExpired,proposalContentHash,transitionStatus,validatePaymentMilestones } from "./proposal-domain";
import type { ProposalAction,ProposalStatus } from "./proposal-domain";

const APPROVED_SCOPE=["approved_internal","ready_for_client","sent","viewed","negotiation","client_changes_requested","approved","signed"];
const SENSITIVE=new Set(["internally_approved","proposal_sent","proposal_expired"]);
type CreateInput={pricing?:any[];tax?:{type:string;rate:number};currency?:string;paymentMilestones?:any[];validUntil?:string;clientContent?:Record<string,unknown>;internalNotes?:string};

export async function recordProposalEvent(input:{proposalId:string;proposalVersionId?:string|null;actorId?:string|null;actorType:"admin"|"client"|"system";event:string;clientId?:string|null;companyId?:string|null;metadata?:Record<string,unknown>}){const {error}=await supabaseAdmin.from("commercial_document_activity").insert({document_type:"proposal",document_id:input.proposalId,proposal_version_id:input.proposalVersionId||null,actor_id:input.actorId||null,actor_type:input.actorType,event_type:input.event,metadata:input.metadata||{}});if(error)throw new Error(error.message);if(SENSITIVE.has(input.event))await recordAuditEvent({actorId:input.actorId,action:input.event,resourceType:"commercial_proposal",resourceId:input.proposalId,clientId:input.clientId,companyId:input.companyId,metadata:{proposalVersionId:input.proposalVersionId,...input.metadata}});}
function snapshot(proposal:any){return{proposal:{id:proposal.id,number:proposal.proposal_number,status:proposal.status,version:proposal.version},engagement:{assessmentId:proposal.assessment_id,clientId:proposal.client_id,companyId:proposal.company_id,dealId:proposal.deal_id,solutionArchitectureId:proposal.solution_architecture_id,scopeOfWorkId:proposal.scope_of_work_id},clientContent:proposal.client_content,pricing:proposal.pricing,commercialTotals:proposal.commercial_totals,paymentSchedule:proposal.payment_schedule,validUntil:proposal.valid_until,createdAt:proposal.updated_at||proposal.created_at,createdBy:proposal.created_by};}
async function createVersion(proposal:any,userId:string,clientVisible=false){const body=snapshot(proposal),hash=proposalContentHash(body);const {data,error}=await supabaseAdmin.from("commercial_document_versions").insert({document_type:"proposal",document_id:proposal.id,version:proposal.version,snapshot:body,content_hash:hash,locked_at:new Date().toISOString(),client_visible:clientVisible,created_by:userId}).select("id,content_hash").single();if(error)throw new Error(error.message);const updated=await supabaseAdmin.from("commercial_proposals").update({current_version_id:data.id,content_hash:hash}).eq("id",proposal.id);if(updated.error)throw new Error(updated.error.message);await recordProposalEvent({proposalId:proposal.id,proposalVersionId:data.id,actorId:userId,actorType:"admin",event:"proposal_version_created",clientId:proposal.client_id,companyId:proposal.company_id,metadata:{version:proposal.version,contentHash:hash,clientVisible}});return data;}
async function engagement(scopeId:string){const {data:scope,error}=await supabaseAdmin.from("scopes_of_work").select("*").eq("id",scopeId).maybeSingle();if(error)throw new Error(error.message);if(!scope)throw new ConsultingHttpError(404,"Scope of Work not found.");if(!APPROVED_SCOPE.includes(scope.status))throw new ConsultingHttpError(409,"Approve the Scope of Work before creating a proposal.");const {data:architecture,error:architectureError}=await supabaseAdmin.from("solution_architectures").select("*").eq("id",scope.solution_architecture_id).maybeSingle();if(architectureError)throw new Error(architectureError.message);if(!architecture)throw new ConsultingHttpError(409,"The related Solution Architecture is missing.");for(const key of ["assessment_id","client_id","company_id","deal_id"]){if((scope[key]||null)!==(architecture[key]||null))throw new ConsultingHttpError(409,`Engagement relationship mismatch: ${key}.`);}return{scope,architecture};}
export async function createCanonicalProposal(scopeId:string,userId:string,input:CreateInput={}){const {scope,architecture}=await engagement(scopeId);const existing=await supabaseAdmin.from("commercial_proposals").select("*").eq("scope_of_work_id",scopeId).not("status","eq","archived").maybeSingle();if(existing.error)throw new Error(existing.error.message);if(existing.data)return existing.data;let pricing:any[]=[],commercialTotals:Record<string,unknown>={};if(input.pricing?.length){const result=calculateCommercials(input.pricing,input.tax||{type:"Tax",rate:0},input.currency||"INR");pricing=result.lines;commercialTotals=result.totals;}const paymentSchedule=input.paymentMilestones?.length?validatePaymentMilestones(input.paymentMilestones):[];const scopeContent=scope.content||{};const clientContent={executiveSummary:scopeContent.executiveSummary||{content:"Draft — Requires Human Review"},scope:scopeContent.included||[],deliverables:scopeContent.deliverables||[],timeline:scopeContent.milestones||[],milestones:scopeContent.milestones||[],assumptions:scopeContent.assumptions||[],exclusions:scopeContent.exclusions||[],terms:[],nextSteps:[],...(input.clientContent||{})};const {data,error}=await supabaseAdmin.from("commercial_proposals").insert({scope_of_work_id:scope.id,solution_architecture_id:architecture.id,assessment_id:scope.assessment_id,client_id:scope.client_id,company_id:scope.company_id,deal_id:scope.deal_id,created_by:userId,client_content:clientContent,internal_notes:input.internalNotes||null,content:{sourceScope:scope.scope_number},pricing,commercial_totals:commercialTotals,payment_schedule:paymentSchedule,valid_until:input.validUntil||null}).select("*").single();if(error)throw new Error(error.message);await recordProposalEvent({proposalId:data.id,actorId:userId,actorType:"admin",event:"proposal_created",clientId:data.client_id,companyId:data.company_id,metadata:{scopeNumber:scope.scope_number}});await createVersion(data,userId,false);return data;}
const EVENT_BY_ACTION:Record<ProposalAction,string>={request_internal_review:"internal_review_requested",request_internal_changes:"changes_requested",approve_internal:"internally_approved",mark_ready_for_client:"proposal_updated",send:"proposal_sent",mark_viewed:"proposal_viewed",mark_expired:"proposal_expired",cancel:"proposal_updated",archive:"proposal_updated",revise:"proposal_revised"};
export async function transitionCanonicalProposal(id:string,action:ProposalAction,userId:string){const {data:proposal,error}=await supabaseAdmin.from("commercial_proposals").select("*").eq("id",id).maybeSingle();if(error)throw new Error(error.message);if(!proposal)throw new ConsultingHttpError(404,"Proposal not found.");if(action==="send"&&isExpired(proposal.valid_until))throw new ConsultingHttpError(409,"Expired proposals cannot be sent.");let next:ProposalStatus;try{next=transitionStatus(proposal.status as ProposalStatus,action);}catch(error){throw new ConsultingHttpError(409,(error as Error).message);}const now=new Date().toISOString(),updates:any={status:next,updated_at:now};if(next==="approved_internal"){updates.approved_by=userId;updates.approved_at=now;}if(next==="sent")updates.sent_at=now;if(next==="viewed")updates.viewed_at=now;if(next==="expired")updates.expired_at=now;const result=await supabaseAdmin.from("commercial_proposals").update(updates).eq("id",id).eq("status",proposal.status).select("*").single();if(result.error)throw new Error(result.error.message);let versionId=proposal.current_version_id;if(["approved_internal","ready_for_client","sent"].includes(next)){const nextVersion=Number(result.data.version)+1;const version=await createVersion({...result.data,version:nextVersion},userId,true);versionId=version.id;await supabaseAdmin.from("commercial_proposals").update({version:nextVersion}).eq("id",id);}await recordProposalEvent({proposalId:id,proposalVersionId:versionId,actorId:userId,actorType:"admin",event:EVENT_BY_ACTION[action],clientId:proposal.client_id,companyId:proposal.company_id,metadata:{from:proposal.status,to:next}});return{...result.data,status:next};}
