import "server-only";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/auth";
import { supabaseAdmin } from "@/lib/supabase/admin";
import { ConsultingHttpError, workflowError } from "@/lib/consulting/workflow";
import { compileMasterServiceAgreement } from "@/lib/commercial/msa";

export const COMMERCIAL_STATUSES=["draft","internal_review","changes_required","approved_internal","ready_for_client","sent","viewed","negotiation","client_changes_requested","approved","rejected","expired","signed","cancelled","archived"] as const;
export async function requireCommercialAdmin(){const session=await getServerSession(authOptions);if(!session?.user?.id)throw new ConsultingHttpError(401,"Authentication required.");if(!["ADMIN","CO_ADMIN"].includes(session.user.role))throw new ConsultingHttpError(403,"Commercial workspace permission is required.");return {userId:session.user.id};}
export async function requireCommercialClient(){const session=await getServerSession(authOptions);if(!session?.user?.id||session.user.role!=="CLIENT")throw new ConsultingHttpError(403,"A client account is required.");const {data}=await supabaseAdmin.from("client_profiles").select("id").eq("user_id",session.user.id).maybeSingle();if(!data)throw new ConsultingHttpError(403,"Client account is not linked.");return {userId:session.user.id,clientId:data.id};}
export function commercialError(error:unknown){return workflowError(error);}
const approvedArchitecture=["approved_internal","ready_for_client","shared","client_reviewed","client_acknowledged","closed"];
const approvedScope=["approved_internal","ready_for_client","sent","viewed","negotiation","client_changes_requested","approved","signed"];
async function activity(type:string,id:string,actorId:string,event:string,metadata:Record<string,unknown>={}){const {error}=await supabaseAdmin.from("commercial_document_activity").insert({document_type:type,document_id:id,actor_id:actorId,actor_type:"admin",event_type:event,metadata});if(error)throw new Error(error.message);}
export async function createScope(architectureId:string,userId:string){const {data:architecture,error}=await supabaseAdmin.from("solution_architectures").select("*").eq("id",architectureId).maybeSingle();if(error)throw new Error(error.message);if(!architecture)throw new ConsultingHttpError(404,"Solution Architecture not found.");if(!approvedArchitecture.includes(architecture.status))throw new ConsultingHttpError(409,"Approve the Solution Architecture before creating a Scope of Work.");const existing=await supabaseAdmin.from("scopes_of_work").select("id,scope_number").eq("solution_architecture_id",architectureId).not("status","eq","archived").maybeSingle();if(existing.data)return existing.data;const payload={solution_architecture_id:architecture.id,ai_solution_report_id:architecture.ai_solution_report_id,audit_id:architecture.audit_id,assessment_id:architecture.assessment_id,discovery_meeting_id:architecture.discovery_meeting_id,client_id:architecture.client_id,company_id:architecture.company_id,deal_id:architecture.deal_id,created_by:userId,content:{sourceArchitecture:architecture.architecture_number,executiveSummary:{content:"Draft — Requires Human Review"},included:architecture.business_capabilities||[],deliverables:[],exclusions:[],deferred:[],assumptions:[],dependencies:[],acceptanceCriteria:[],traceability:[]}};const {data,error:insertError}=await supabaseAdmin.from("scopes_of_work").insert(payload).select("*").single();if(insertError)throw new Error(insertError.message);await activity("scope",data.id,userId,"scope_created",{architectureNumber:architecture.architecture_number});return data;}
export async function createProposal(scopeId:string,userId:string){const {data:scope,error}=await supabaseAdmin.from("scopes_of_work").select("*").eq("id",scopeId).maybeSingle();if(error)throw new Error(error.message);if(!scope)throw new ConsultingHttpError(404,"Scope of Work not found.");if(!approvedScope.includes(scope.status))throw new ConsultingHttpError(409,"Approve the Scope of Work before creating a proposal.");const existing=await supabaseAdmin.from("commercial_proposals").select("id,proposal_number").eq("scope_of_work_id",scopeId).not("status","eq","archived").maybeSingle();if(existing.data)return existing.data;const {data:architecture}=await supabaseAdmin.from("solution_architectures").select("id").eq("id",scope.solution_architecture_id).single();const payload={scope_of_work_id:scope.id,solution_architecture_id:architecture?.id||scope.solution_architecture_id,client_id:scope.client_id,company_id:scope.company_id,deal_id:scope.deal_id,created_by:userId,content:{sourceScope:scope.scope_number,executiveSummary:{content:"Draft — Requires Human Review"},deliverables:scope.content?.deliverables||[],timeline:scope.content?.milestones||[],exclusions:scope.content?.exclusions||[]},pricing:[],payment_schedule:[]};const {data,error:insertError}=await supabaseAdmin.from("commercial_proposals").insert(payload).select("*").single();if(insertError)throw new Error(insertError.message);await activity("proposal",data.id,userId,"proposal_created",{scopeNumber:scope.scope_number});return data;}
export async function createAgreement(proposalId:string,userId:string){return compileMasterServiceAgreement(proposalId,userId);}
export { supabaseAdmin };
