import "server-only";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/auth";
import { supabaseAdmin } from "@/lib/supabase/admin";

export const AUDIT_STATUSES=["Draft","Internal Review","Ready for Client","Shared","Client Reviewed","Closed"] as const;
export class AuditHttpError extends Error{constructor(public status:number,message:string){super(message);}}
export async function requireAuditAdmin(){const session=await getServerSession(authOptions);if(!session?.user?.id)throw new AuditHttpError(401,"Authentication required.");if(!["ADMIN","CO_ADMIN"].includes(session.user.role))throw new AuditHttpError(403,"Audit administration permission is required.");return {userId:session.user.id};}
export async function requireAuditClient(){const session=await getServerSession(authOptions);if(!session?.user?.id||session.user.role!=="CLIENT")throw new AuditHttpError(403,"A client account is required.");const {data}=await supabaseAdmin.from("client_profiles").select("id").eq("user_id",session.user.id).maybeSingle();if(!data)throw new AuditHttpError(403,"Client account is not linked.");return {userId:session.user.id,clientId:data.id};}
export function auditError(error:unknown){return Response.json({error:error instanceof Error?error.message:"Audit request failed."},{status:error instanceof AuditHttpError?error.status:500});}
const answerMap=(answers:unknown)=>Object.fromEntries(Array.isArray(answers)?answers.map((item)=>{const row=item as {question_key?:string;value?:unknown};return [row.question_key||"",row.value];}).filter(([key])=>Boolean(key)):[]);
export async function createAudit(input:{discoveryMeetingId:string},userId:string){
  const {data:meeting,error}=await supabaseAdmin.from("discovery_meetings").select("*").eq("id",input.discoveryMeetingId).maybeSingle();
  if(error)throw new Error(error.message);if(!meeting)throw new AuditHttpError(404,"Discovery meeting not found.");if(meeting.status!=="closed")throw new AuditHttpError(409,"Close the discovery meeting before creating the audit.");
  const existing=await supabaseAdmin.from("business_technical_audits").select("id,audit_number").eq("discovery_meeting_id",meeting.id).not("status","eq","Closed").maybeSingle();if(existing.data)return existing.data;
  const [assessment,findings,requirements,risks,decisions,actions]=await Promise.all([supabaseAdmin.from("client_assessments").select("assessment_number,assessment_answers(*)").eq("id",meeting.assessment_id).maybeSingle(),supabaseAdmin.from("discovery_findings").select("*").eq("meeting_id",meeting.id),supabaseAdmin.from("discovery_requirements").select("*").eq("meeting_id",meeting.id),supabaseAdmin.from("discovery_risks").select("*").eq("meeting_id",meeting.id),supabaseAdmin.from("discovery_decisions").select("*").eq("meeting_id",meeting.id),supabaseAdmin.from("discovery_action_items").select("*").eq("meeting_id",meeting.id)]);
  const answers=answerMap(assessment.data?.assessment_answers);
  const payload={discovery_meeting_id:meeting.id,assessment_id:meeting.assessment_id,client_id:meeting.client_id,company_id:meeting.company_id,deal_id:meeting.deal_id,status:"Draft",executive_summary:{companyOverview:answers.business_overview||answers.company_overview||"",businessObjective:answers.business_objectives||"",assessmentSummary:"Prepared from the submitted assessment and closed discovery meeting.",keyFindings:findings.data||[],overallConclusion:"Consultant review required."},business_overview:answers,operating_model:{},technology_landscape:{},digital_presence:{},business_challenges:findings.data||[],technical_challenges:[],process_gaps:[],technology_gaps:[],ai_readiness:{},risks:risks.data||[],quick_wins:[],medium_term_opportunities:[],long_term_opportunities:[],priority_matrix:[],recommendations:[],next_steps:[{title:"AI Opportunity & Solution Report",status:"Locked until audit approval"}],created_by:userId};
  const {data,error:insertError}=await supabaseAdmin.from("business_technical_audits").insert(payload).select("*").single();if(insertError)throw new Error(insertError.message);
  await supabaseAdmin.from("business_audit_activity").insert({audit_id:data.id,actor_id:userId,actor_type:"admin",event_type:"audit_created",metadata:{assessmentNumber:assessment.data?.assessment_number||null,requirements:requirements.data?.length||0,decisions:decisions.data?.length||0,actions:actions.data?.length||0}});return data;
}
