import type { ContractorAgreementSnapshot } from "@/lib/contractors/agreements";

const date = (value: string | null) => value ? new Date(value).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" }) : "Not specified";
const value = (item: unknown) => item === null || item === undefined || item === "" ? "Not specified" : String(item);

export function ContractorAgreementDocument({ snapshot, showInternal = false }: { snapshot: ContractorAgreementSnapshot; showInternal?: boolean }) {
  const unresolved = snapshot.legalFields.filter((field) => field.status === "unresolved");
  return <article className="contractor-agreement-document mx-auto max-w-5xl border border-slate-200 bg-white text-slate-900 shadow-sm">
    <header className="border-b-2 border-slate-900 p-8 sm:p-12"><div className="flex items-start justify-between gap-5"><div><p className="text-xl font-bold">GrowX<span className="text-[#1d5f8d]">Labs.tech</span></p><p className="mt-5 text-xs font-semibold uppercase tracking-[0.2em] text-[#1d5f8d]">Contractor agreement</p></div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-red-700">Confidential</p></div><h2 className="mt-3 font-serif text-3xl leading-tight sm:text-4xl">{snapshot.document.title}</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-600">{snapshot.document.status === "fully_executed" || snapshot.document.status === "completed" ? "Canonical executed copy generated from the signed agreement snapshot." : "Internal draft for GrowxLabs completion and review."}</p><div className="mt-7 grid gap-5 border-t border-slate-200 pt-5 sm:grid-cols-3"><Meta label="Agreement number" value={snapshot.document.agreementNumber} /><Meta label="Version" value={`Version ${snapshot.document.version}`} /><Meta label="Status" value={snapshot.document.status.replaceAll("_", " ")} /><Meta label="Contractor" value={snapshot.parties.contractor.fullLegalName} /><Meta label="Project role" value={snapshot.parties.contractor.role} /><Meta label="Project" value={snapshot.project.projectName} /><Meta label="Agreement date" value={date(snapshot.document.agreementDate)} /><Meta label="Effective date" value={date(snapshot.document.effectiveDate)} /><Meta label="Total fee" value="₹30,000" /></div></header>
    {showInternal && unresolved.length ? <section className="m-8 rounded-lg border border-amber-300 bg-amber-50 p-5 sm:m-12"><p className="text-xs font-bold uppercase tracking-wider text-amber-800">Internal completion required</p><p className="mt-2 text-sm text-amber-950">Complete these fields before approving the agreement for signing:</p><ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-amber-900">{unresolved.map((field) => <li key={field.key}>{field.label}</li>)}</ul></section> : null}
    <div className="p-8 sm:p-12">{snapshot.sections.map((section) => <section key={section.key} className="mb-9"><div className="mb-3 flex gap-3"><span className="font-serif text-xl text-[#1d4f7a]">{String(section.number).padStart(2, "0")}</span><h3 className="font-serif text-xl text-slate-900">{section.title}</h3></div>{section.body.map((paragraph, index) => <p key={index} className="mb-3 text-sm leading-7 text-slate-700">{paragraph}</p>)}{section.items?.length ? <ul className="mb-3 list-disc space-y-2 pl-5 text-sm leading-6 text-slate-700">{section.items.map((item, index) => <li key={index}>{item}</li>)}</ul> : null}{section.fields?.length ? <dl className="overflow-hidden border-y border-slate-200">{section.fields.map((field) => <div key={field.label} className="grid gap-2 border-b border-slate-100 py-3 last:border-b-0 sm:grid-cols-[220px_1fr]"><dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">{field.label}</dt><dd className={field.value ? "text-sm leading-6 text-slate-800" : "text-sm italic text-amber-700"}>{value(field.value)}</dd></div>)}</dl> : null}</section>)}
      <section className="border-t-2 border-slate-900 pt-8"><h3 className="font-serif text-2xl">Signatures</h3><div className="mt-5 grid gap-5 md:grid-cols-2"><Signature party="GrowxLabs" signature={snapshot.signatures.find((item) => item.party === "growxlabs")} /><Signature party="Contractor" signature={snapshot.signatures.find((item) => item.party === "contractor")} /></div>{snapshot.execution ? <p className="mt-5 text-xs text-slate-600">Final execution timestamp: {date(snapshot.execution.executedAt)} · Document hash: {snapshot.execution.documentHash}</p> : null}</section>
    </div>
    <footer className="flex justify-between border-t border-slate-200 px-8 py-4 text-xs text-slate-500 sm:px-12"><span>{snapshot.document.agreementNumber} · Version {snapshot.document.version} · Confidential</span><span>GrowxLabs</span></footer>
  </article>;
}

function Meta({ label, value: metaValue }: { label: string; value: string | null }) { return <div><p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-1 text-sm text-slate-900">{value(metaValue)}</p></div>; }
function Signature({ party, signature }: { party: string; signature?: ContractorAgreementSnapshot["signatures"][number] }) { return <div className="rounded-lg border border-slate-200 p-5"><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">For {party}</p><p className="mt-5 text-sm font-semibold">{signature?.fullLegalName || "Not signed"}</p><p className="mt-1 text-sm text-slate-600">{signature?.roleOrCapacity || "Authorised signatory"}</p><p className="mt-1 text-sm text-slate-600">{signature?.email || "Not signed"}</p><p className="mt-5 border-t border-slate-300 pt-2 text-xs text-slate-500">Signature date: {signature ? date(signature.signedAt) : "Not signed"}</p></div>; }
