/* eslint-disable @typescript-eslint/no-explicit-any */
import { createAdvanceInvoice, financeError, issueConsultingInvoice, requireFinanceAdmin, supabaseAdmin } from "@/lib/finance/activation-workflow";

export async function GET() {
  try { await requireFinanceAdmin(); const { data, error } = await supabaseAdmin.from("consulting_advance_invoices").select("id,invoice_number,status,currency,subtotal,discount_total,tax_total,total,amount_paid,balance_due,tax_breakdown,line_items,payment_instructions,due_date,issued_at,sent_at,created_at,client_id,company_id,agreement_id,proposal_id,scope_id").order("created_at", { ascending: false }); if (error) throw new Error(error.message); const invoices = await Promise.all((data || []).map(async (invoice: Record<string, any>) => { const [agreement, proposal, scope, activity] = await Promise.all([supabaseAdmin.from("master_service_agreements").select("agreement_number").eq("id", invoice.agreement_id).maybeSingle(), supabaseAdmin.from("commercial_proposals").select("proposal_number").eq("id", invoice.proposal_id).maybeSingle(), supabaseAdmin.from("scopes_of_work").select("scope_number").eq("id", invoice.scope_id).maybeSingle(), supabaseAdmin.from("finance_activation_activity").select("event_type,metadata,created_at").eq("entity_type", "invoice").eq("entity_id", invoice.id).order("created_at", { ascending: false })]); return { ...invoice, agreementReference: agreement.data?.agreement_number || null, proposalReference: proposal.data?.proposal_number || null, scopeReference: scope.data?.scope_number || null, activity: activity.data || [] }; })); return Response.json({ invoices }); } catch (error) { return financeError(error); }
}

export async function POST(request: Request) {
  try { const { userId } = await requireFinanceAdmin(); const body = await request.json() as { agreementId?: string; invoiceId?: string; milestoneIndex?: number; triggerConfirmed?: boolean; action?: "create" | "issue" }; if (body.action === "issue") { if (!body.invoiceId) return Response.json({ error: "Invoice is required." }, { status: 400 }); return Response.json({ invoice: await issueConsultingInvoice(body.invoiceId, userId) }); } if (!body.agreementId) return Response.json({ error: "Agreement is required." }, { status: 400 }); return Response.json({ invoice: await createAdvanceInvoice(body.agreementId, userId, Number(body.milestoneIndex || 0), body.triggerConfirmed === true) }, { status: 201 }); } catch (error) { return financeError(error); }
}
