"use client";
import {useCallback,useEffect,useState} from "react";
import {BookOpen,Box,FileCheck2,Loader2,UploadCloud} from "lucide-react";
type Domain="documents"|"assets"|"learning";
type Item=Record<string,unknown>;
const config={
 documents:{title:"Documents",subtitle:"Secure files, requests and verification",icon:FileCheck2,list:"/api/v1/hrms/documents/documents"},
 assets:{title:"Assets",subtitle:"Assigned equipment and lifecycle",icon:Box,list:"/api/v1/hrms/assets/assets"},
 learning:{title:"Learning",subtitle:"Courses, progress and certificates",icon:BookOpen,list:"/api/v1/hrms/learning/enrollments"},
} as const;
export default function Release05Workspace({domain,scope="self"}:{domain:Domain;scope?:"self"|"team"|"admin"}){
 const c=config[domain],Icon=c.icon,[items,setItems]=useState<Item[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true),[query,setQuery]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{let url:string=c.list;if(domain==="documents"&&scope==="self"){const profile=await fetch("/api/v1/hrms/people/me").then(r=>r.json());url+=`?ownerEntityType=employee&ownerEntityId=${encodeURIComponent(profile.id||"")}`}else if(domain==="documents"){url="/api/v1/hrms/documents/documents/requests"}const response=await fetch(url),body=await response.json();if(!response.ok)throw new Error(body.detail||body.error);setItems(body.items||body||[])}catch(value){setError(value instanceof Error?value.message:"Unable to load workspace")}finally{setLoading(false)}},[c.list,domain,scope]);
 useEffect(()=>{void load()},[load]);const filtered=items.filter(item=>JSON.stringify(item).toLowerCase().includes(query.toLowerCase()));
 return <main className="mx-auto min-h-screen max-w-7xl px-5 py-10 text-neutral-900"><header className="flex flex-wrap items-end justify-between gap-4 border-b border-neutral-200 pb-7"><div><p className="text-[10px] font-bold uppercase tracking-[.22em] text-[#0075de]">{scope==="admin"?"HR administration":scope==="team"?"Manager workspace":"Employee self-service"}</p><h1 className="mt-2 flex items-center gap-3 text-3xl font-black"><Icon className="text-[#0075de]"/>{c.title}</h1><p className="mt-2 text-sm text-neutral-500">{c.subtitle}</p></div>{domain==="documents"&&scope==="self"&&<a href="/me/documents/upload" className="flex items-center gap-2 rounded-xl bg-[#0075de] px-4 py-2.5 text-xs font-bold text-white"><UploadCloud size={15}/>Upload document</a>}</header><div className="mt-6 flex gap-3"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${c.title.toLowerCase()}…`} className="h-11 flex-1 rounded-xl border border-neutral-200 px-4 text-sm"/><button onClick={()=>void load()} className="rounded-xl border border-neutral-200 px-4 text-xs font-bold">Refresh</button></div>{error&&<div className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}{loading?<div className="flex h-64 items-center justify-center"><Loader2 className="animate-spin text-[#0075de]"/></div>:<section className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map((item,index)=><article key={String(item.id||index)} className="rounded-2xl border border-neutral-200 bg-white p-5"><div className="flex items-start justify-between gap-3"><h2 className="font-extrabold">{String(item.name||item.title||item.requestedName||item.assetCode||"Record")}</h2><span className="rounded-full bg-blue-50 px-2 py-1 text-[9px] font-bold text-blue-700">{String(item.status||item.state||item.verificationStatus||"ACTIVE")}</span></div><dl className="mt-4 space-y-2">{Object.entries(item).filter(([key])=>!["id","name","title","status","state"].includes(key)).slice(0,5).map(([key,value])=><div key={key} className="flex justify-between gap-3 text-xs"><dt className="capitalize text-neutral-400">{key.replaceAll(/([A-Z])/g," $1")}</dt><dd className="max-w-[60%] truncate font-semibold">{typeof value==="object"?JSON.stringify(value):String(value??"—")}</dd></div>)}</dl></article>)}</section>}{!loading&&!filtered.length&&!error&&<div className="mt-6 rounded-2xl border border-dashed border-neutral-300 p-14 text-center text-sm text-neutral-400">No records found.</div>}</main>
}
