"use client";

import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { CheckCircle2, CircleAlert, FileSignature } from "lucide-react";

type Offer = { status: string; expiresAt?: string; candidate: string; title: string; joiningDate: string; employmentType: string; workLocation?: string; salaryAmount?: number; salaryCurrency?: string; benefits: string[]; probationDays?: number; noticePeriodDays?: number };

export default function OfferDecision({ token }: { token: string }) {
  const [comment, setComment] = useState(""); const [result, setResult] = useState("");
  const offer = useQuery<Offer>({ queryKey: ["public-offer", token], queryFn: async () => { const response = await fetch(`/api/v1/hrms/onboarding/public/offers/${token}`); const body = await response.json(); if (!response.ok) throw new Error(body.detail || body.error); return body; } });
  async function respond(responseValue: "accepted"|"rejected"|"changes_requested") { const response = await fetch(`/api/v1/hrms/onboarding/public/offers/${token}/respond`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ response: responseValue, comment }) }); const body = await response.json(); if (!response.ok) { setResult(body.detail || body.error); return; } setResult(responseValue); }
  if (offer.isLoading) return <main className="min-h-screen bg-slate-50 p-8 pt-28"><div className="mx-auto h-96 max-w-3xl animate-pulse rounded-3xl bg-slate-200" /></main>;
  if (offer.isError || !offer.data) return <main className="flex min-h-screen items-center justify-center bg-slate-50"><div className="text-center"><CircleAlert className="mx-auto text-red-500" /><h1 className="mt-4 text-2xl font-black">This offer is unavailable</h1><p className="mt-2 text-sm text-slate-500">It may have expired, been withdrawn, or already received a response.</p></div></main>;
  const data = offer.data;
  return <main className="min-h-screen bg-slate-50 px-5 pb-20 pt-24 text-slate-950"><article className="mx-auto max-w-3xl rounded-3xl border border-slate-200 bg-white p-7 shadow-sm sm:p-12"><FileSignature className="text-[#0075de]" size={34}/><div className="mt-6 text-[10px] font-bold uppercase tracking-[.2em] text-[#0075de]">Employment offer</div><h1 className="mt-2 text-4xl font-black">{data.title}</h1><p className="mt-3 text-lg text-slate-600">Prepared for {data.candidate}</p><div className="mt-8 grid gap-3 rounded-2xl bg-slate-50 p-5 sm:grid-cols-2">{[["Joining date",new Date(data.joiningDate).toLocaleDateString()],["Employment",data.employmentType],["Location",data.workLocation||"To be confirmed"],["Compensation",data.salaryAmount?`${data.salaryCurrency||"INR"} ${data.salaryAmount.toLocaleString()}`:"As discussed"],["Probation",data.probationDays?`${data.probationDays} days`:"Not specified"],["Notice period",data.noticePeriodDays?`${data.noticePeriodDays} days`:"Not specified"]].map(([label,value])=><div key={label}><p className="text-[9px] font-bold uppercase tracking-wider text-slate-400">{label}</p><b className="mt-1 block text-sm">{value}</b></div>)}</div>{data.benefits?.length>0&&<section className="mt-7"><h2 className="text-sm font-black">Benefits</h2><ul className="mt-3 grid gap-2 text-sm text-slate-600">{data.benefits.map(item=><li key={item}>• {item}</li>)}</ul></section>}{result?<div className="mt-8 rounded-2xl bg-emerald-50 p-6 text-center text-emerald-700"><CheckCircle2 className="mx-auto"/><b className="mt-3 block">Response recorded: {result.replace("_"," ")}</b></div>:<div className="mt-8"><textarea value={comment} onChange={event=>setComment(event.target.value)} placeholder="Optional comment or requested changes" className="min-h-24 w-full rounded-xl border border-slate-200 p-3 text-sm"/><div className="mt-3 grid gap-2 sm:grid-cols-3"><button onClick={()=>void respond("accepted")} className="rounded-xl bg-emerald-600 px-4 py-3 text-xs font-bold text-white">Accept offer</button><button onClick={()=>void respond("changes_requested")} className="rounded-xl border border-amber-300 px-4 py-3 text-xs font-bold text-amber-700">Request changes</button><button onClick={()=>void respond("rejected")} className="rounded-xl border border-red-300 px-4 py-3 text-xs font-bold text-red-700">Reject offer</button></div></div>}</article></main>;
}
