"use client";
import { useEffect, useState } from "react";

export default function ChangeRequestsPage() {
  const [changes, setChanges] = useState<any[]>([]);
  const [error, setError] = useState("");
  useEffect(() => { fetch("/api/admin/change-requests").then(async (r) => { const body = await r.json(); if (!r.ok) throw new Error(body.error || "Unable to load change requests"); setChanges(body.changes || []); }).catch((e) => setError(e.message)); }, []);
  return <main className="mx-auto max-w-6xl space-y-6 p-8"><div><p className="text-xs font-bold uppercase tracking-widest text-[#0075de]">Delivery operations</p><h1 className="mt-2 text-3xl font-black">Change Requests</h1><p className="mt-2 text-sm text-slate-500">Review client-requested scope and delivery changes.</p></div>{error ? <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div> : <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Request</th><th className="px-5 py-3">Title</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Impact</th><th className="px-5 py-3">Created</th></tr></thead><tbody>{changes.length ? changes.map((item) => <tr key={item.id} className="border-t border-slate-100"><td className="px-5 py-4 font-semibold">{item.change_number || item.id}</td><td className="px-5 py-4">{item.title}</td><td className="px-5 py-4">{item.status}</td><td className="px-5 py-4">{item.impact || "—"}</td><td className="px-5 py-4 text-slate-500">{item.created_at ? new Date(item.created_at).toLocaleString() : "—"}</td></tr>) : <tr><td colSpan={5} className="px-5 py-12 text-center text-slate-500">No change requests found.</td></tr>}</tbody></table></div>}</main>;
}
