"use client";
import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import type { ClientAssessment } from "@/types/assessment";

async function load(){const response=await fetch("/api/client/assessment",{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error||"Unable to load client lifecycle.");return body as {assessment:ClientAssessment|null};}

export default function ClientDashboard(){const query=useQuery({queryKey:["client","assessment"],queryFn:load});if(query.isPending)return <StateCard title="Loading your client workspace"/>;if(query.error)return <StateCard title="Client workspace unavailable" detail={query.error.message}/>;const assessment=query.data.assessment;if(!assessment)return <DashboardShell><StateCard title="Welcome to GrowXLabs" detail="Before we prepare recommendations, complete your Business Discovery & Consulting Assessment. It helps our consulting team understand your business, operations, current systems, challenges, AI opportunities and project readiness." action={{href:"/client/assessment",label:"Start Assessment"}} status="Not started" progress="0 of 12 sections"/></DashboardShell>;
  const count=assessment.completedSections.length; const common={status:label(assessment.status),progress:`${count} of ${assessment.template.sections.length} sections · ${assessment.completionPercentage}%`};
  if(["not_started","draft"].includes(assessment.status))return <DashboardShell><StateCard title="Business Discovery & Consulting Assessment" detail={`Last saved: ${new Date(assessment.updatedAt).toLocaleString()}`} action={{href:"/client/assessment",label:count?"Continue Assessment":"Start Assessment"}} {...common}/></DashboardShell>;
  if(assessment.status==="more_information_required"){const request=assessment.informationRequests.find((item)=>["open","sent","in_progress","changes_required"].includes(item.status));return <DashboardShell><StateCard title="Additional Information Required" detail={request?.message||"Our consulting team has requested updates to selected answers or documents."} action={request?{href:`/client/assessment/information-request/${request.id}`,label:"Provide Requested Information"}:undefined} status="Original Assessment: Submitted" progress="Requested updates are pending"/></DashboardShell>};
  if(assessment.status==="under_review")return <DashboardShell><StateCard title="Consulting Review in Progress" detail="Our team is reviewing your business information, systems, goals, AI opportunities and project readiness." action={{href:"/client/assessment/review",label:"View Assessment"}} status="Under review" progress="Next step: Discovery Meeting"/></DashboardShell>;
  if(assessment.status==="review_complete")return <DashboardShell><StateCard title="Assessment Review Complete" detail="Your assessment review is complete. The next step is the discovery meeting." action={{href:"/client/assessment/review",label:"View Assessment"}} status="Review complete" progress="Next step: Discovery Meeting"/></DashboardShell>;
  return <DashboardShell><StateCard title="Assessment Submitted" detail={`Submitted on: ${assessment.submittedAt?new Date(assessment.submittedAt).toLocaleString():"Recorded"}`} action={{href:"/client/assessment/review",label:"View Submitted Assessment"}} status="Submitted" progress="Current stage: Consulting Review · Next step: Discovery Meeting"/></DashboardShell>;
}
function label(status:ClientAssessment["status"]){return status.split("_").map((part)=>part[0].toUpperCase()+part.slice(1)).join(" ");}
function DashboardShell({children}:{children:React.ReactNode}){return <div className="mx-auto max-w-5xl space-y-6 pb-12"><header><h1 className="text-3xl font-bold tracking-tight text-slate-900">Client Portal</h1><p className="mt-2 text-sm text-slate-600">Your secure GrowXLabs consulting workspace.</p></header>{children}<div className="grid gap-4 md:grid-cols-3"><SmallCard title="Assigned contact" detail="GrowXLabs Consulting Team"/><SmallCard title="Secure documents" detail="Available during assessment and review"/><SmallCard title="Help & support" detail="sai@growxlabs.tech"/></div></div>}
function StateCard({title,detail,status,progress,action}:{title:string;detail?:string;status?:string;progress?:string;action?:{href:string;label:string}}){return <section className="rounded-md border border-slate-200 bg-white p-6 shadow-sm md:p-8"><h2 className="font-serif text-3xl text-slate-900">{title}</h2>{detail&&<p className="mt-4 max-w-3xl leading-7 text-slate-600">{detail}</p>}<dl className="mt-6 grid gap-3 text-sm sm:grid-cols-2">{status&&<div><dt className="text-xs font-bold uppercase tracking-wider text-slate-500">Status</dt><dd className="mt-1 font-semibold text-slate-900">{status}</dd></div>}{progress&&<div><dt className="text-xs font-bold uppercase tracking-wider text-slate-500">Progress</dt><dd className="mt-1 font-semibold text-slate-900">{progress}</dd></div>}</dl>{action&&<Link href={action.href} className="mt-7 inline-flex min-h-11 items-center rounded bg-[#1d4f7a] px-5 font-semibold text-white">{action.label}</Link>}</section>}
function SmallCard({title,detail}:{title:string;detail:string}){return <div className="rounded border border-slate-200 bg-white p-5"><h3 className="text-sm font-bold text-slate-900">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{detail}</p></div>}
