"use client";
import { useCallback,useEffect,useState } from "react";
import { CalendarDays,Clock3,Loader2,PlaneTakeoff,RefreshCw } from "lucide-react";

type Today={date:string;events:Array<{id:string;eventType:string;occurredAt:string}>;summary:null|{worked_minutes:number;status:string;late_minutes:number;overtime_minutes:number}};
type Balance={leaveTypeId:string;balance:number;leaveType:{name?:string}|null};
type LeaveRequest={id:string;start_date:string;end_date:string;total_quantity:number;status:string;reason:string};
const button="rounded-xl px-4 py-2.5 text-xs font-bold transition disabled:cursor-not-allowed disabled:opacity-50";

export default function TimeAndLeaveWorkspace(){
  const[today,setToday]=useState<Today|null>(null),[balances,setBalances]=useState<Balance[]>([]),[requests,setRequests]=useState<LeaveRequest[]>([]);
  const[busy,setBusy]=useState(""),[error,setError]=useState("");
  const load=useCallback(async()=>{setError("");try{const responses=await Promise.all([fetch("/api/v1/hrms/attendance/today"),fetch("/api/v1/hrms/leave/balances"),fetch("/api/v1/hrms/leave/requests")]);const bodies=await Promise.all(responses.map(r=>r.json()));const failed=responses.findIndex(r=>!r.ok);if(failed>=0)throw new Error(bodies[failed].detail||bodies[failed].error);setToday(bodies[0]);setBalances(bodies[1].items||[]);setRequests(bodies[2].items||[])}catch(value){setError(value instanceof Error?value.message:"Unable to load time and leave")}finally{setBusy("")}},[]);
  useEffect(()=>{void load()},[load]);
  async function clock(eventType:string){setBusy(eventType);setError("");try{const response=await fetch("/api/v1/hrms/attendance/events",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({eventType,occurredAt:new Date().toISOString(),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone})});const body=await response.json();if(!response.ok)throw new Error(body.detail||body.error);await load()}catch(value){setError(value instanceof Error?value.message:"Clock action failed");setBusy("")}}
  return <main className="mx-auto min-h-screen max-w-6xl px-5 py-12 text-neutral-900">
    <header className="flex flex-wrap items-end justify-between gap-4 border-b border-neutral-200 pb-7"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#0075de]">Employee self-service</p><h1 className="mt-2 text-3xl font-black">Time & leave</h1><p className="mt-1 text-sm text-neutral-500">Clock attendance, review your month, and manage leave.</p></div><button className={`${button} flex items-center gap-2 border border-neutral-200`} onClick={()=>void load()}><RefreshCw size={14}/>Refresh</button></header>
    {error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
    <section className="mt-7 grid gap-5 lg:grid-cols-3">
      <article className="rounded-2xl border border-neutral-200 p-6 lg:col-span-2"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-wider text-neutral-400">Today · {today?.date||"—"}</p><h2 className="mt-1 text-xl font-extrabold">{today?.summary?.status?.replaceAll("_"," ")||"Ready to clock in"}</h2></div><Clock3 className="text-[#0075de]"/></div><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{["CHECK_IN","BREAK_START","BREAK_END","CHECK_OUT"].map(type=><button key={type} disabled={Boolean(busy)} onClick={()=>void clock(type)} className={`${button} ${type==="CHECK_IN"?"bg-[#0075de] text-white":"border border-neutral-200 hover:bg-neutral-50"}`}>{busy===type?<Loader2 className="mx-auto animate-spin" size={15}/>:type.replaceAll("_"," ")}</button>)}</div><div className="mt-6 grid grid-cols-3 gap-3">{[["Worked",today?.summary?.worked_minutes||0],["Late",today?.summary?.late_minutes||0],["Overtime",today?.summary?.overtime_minutes||0]].map(([label,value])=><div key={String(label)} className="rounded-xl bg-neutral-50 p-4"><p className="text-[10px] font-bold uppercase text-neutral-400">{label}</p><p className="mt-1 text-lg font-black">{value}m</p></div>)}</div><ol className="mt-5 space-y-2">{today?.events?.map(event=><li key={event.id} className="flex justify-between border-t border-neutral-100 pt-2 text-xs"><span className="font-bold">{event.eventType.replaceAll("_"," ")}</span><time className="text-neutral-500">{new Date(event.occurredAt).toLocaleTimeString()}</time></li>)}</ol></article>
      <article className="rounded-2xl border border-neutral-200 p-6"><div className="flex items-center gap-2"><PlaneTakeoff size={18} className="text-[#0075de]"/><h2 className="font-extrabold">Leave balances</h2></div><div className="mt-5 space-y-3">{balances.length?balances.map(item=><div key={item.leaveTypeId} className="flex items-center justify-between rounded-xl bg-neutral-50 p-4"><span className="text-xs font-semibold">{item.leaveType?.name||"Leave"}</span><strong>{item.balance} days</strong></div>):<p className="text-xs text-neutral-400">No balance entries yet.</p>}</div><a href="/people/leave/request" className={`${button} mt-5 block bg-neutral-900 text-center text-white`}>Request leave</a></article>
    </section>
    <section className="mt-5 rounded-2xl border border-neutral-200 p-6"><div className="flex items-center gap-2"><CalendarDays size={18} className="text-[#0075de]"/><h2 className="font-extrabold">Recent requests</h2></div><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-xs"><thead className="text-[10px] uppercase text-neutral-400"><tr><th className="pb-3">Dates</th><th className="pb-3">Quantity</th><th className="pb-3">Reason</th><th className="pb-3">Status</th></tr></thead><tbody>{requests.map(item=><tr key={item.id} className="border-t border-neutral-100"><td className="py-3 font-semibold">{item.start_date} — {item.end_date}</td><td>{item.total_quantity}</td><td>{item.reason}</td><td><span className="rounded-full bg-blue-50 px-2 py-1 font-bold text-blue-700">{item.status}</span></td></tr>)}</tbody></table></div></section>
  </main>
}
