import "server-only";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/auth";
import { supabaseAdmin } from "@/lib/supabase/admin";
import { ConsultingHttpError } from "@/lib/consulting/workflow";
export { supabaseAdmin };
const admins = ["ADMIN", "CO_ADMIN"];
export async function requireCommunicationAdmin() { const s = await getServerSession(authOptions); if (!s?.user?.id) throw new ConsultingHttpError(401, "Authentication required."); if (!admins.includes(s.user.role)) throw new ConsultingHttpError(403, "Communication permission is required."); return { userId: s.user.id }; }
export async function requireCommunicationClient() { const s = await getServerSession(authOptions); if (!s?.user?.id || s.user.role !== "CLIENT") throw new ConsultingHttpError(403, "A client account is required."); const { data } = await supabaseAdmin.from("client_profiles").select("id").eq("user_id", s.user.id).maybeSingle(); if (!data) throw new ConsultingHttpError(403, "Client account is not linked."); return { userId: s.user.id, clientId: data.id }; }
export function communicationError(error: unknown) { return Response.json({ error: error instanceof Error ? error.message : "Communication request failed." }, { status: error instanceof ConsultingHttpError ? error.status : 500 }); }
export async function enqueueCommunication(input: Record<string, unknown>, senderId: string) { if (!input.channel || !input.messageType || !input.body || !input.email) throw new ConsultingHttpError(400, "Channel, message type, body, and recipient email are required."); if (input.aiDraft === true) input.status = "draft"; const { data: message, error } = await supabaseAdmin.from("communication_messages").insert({ channel: input.channel, message_type: input.messageType, subject: input.subject || null, body: input.body, variables: input.variables || {}, sender_id: senderId, related_entity_type: input.relatedEntityType || null, related_entity_id: input.relatedEntityId || null, client_id: input.clientId || null, company_id: input.companyId || null, project_id: input.projectId || null, status: input.status || "queued", scheduled_for: input.scheduledFor || null }).select("*").single(); if (error) throw new Error(error.message); const { error: recipientError } = await supabaseAdmin.from("communication_recipients").insert({ message_id: message.id, email: input.email, display_name: input.displayName || null }); if (recipientError) throw new Error(recipientError.message); if (message.status === "queued" || message.status === "scheduled") { const { error: queueError } = await supabaseAdmin.from("communication_queue").insert({ message_id: message.id, status: message.status === "scheduled" ? "scheduled" : "pending", next_attempt_at: input.scheduledFor || new Date().toISOString() }); if (queueError) throw new Error(queueError.message); } await supabaseAdmin.from("communication_events").insert({ message_id: message.id, event_type: "queued", event_data: { channel: input.channel } }); return message; }
export async function recordDeliveryEvent(messageId: string, eventType: string, eventData: Record<string, unknown> = {}) { const allowed = ["sent", "delivered", "opened", "clicked", "bounced", "spam", "failed", "unsubscribed"]; if (!allowed.includes(eventType)) throw new ConsultingHttpError(400, "Unsupported delivery event."); const { error } = await supabaseAdmin.from("communication_events").insert({ message_id: messageId, event_type: eventType, event_data: eventData }); if (error) throw new Error(error.message); const status = eventType === "bounced" || eventType === "spam" ? "failed" : eventType; await supabaseAdmin.from("communication_messages").update({ status, updated_at: new Date().toISOString(), ...(eventType === "sent" ? { sent_at: new Date().toISOString() } : {}) }).eq("id", messageId); return { messageId, eventType }; }
export async function retryCommunication(messageId: string, actorId: string) { const now = new Date().toISOString(); const { data: message, error: messageError } = await supabaseAdmin.from("communication_messages").select("id,status").eq("id", messageId).maybeSingle(); if (messageError) throw new Error(messageError.message); if (!message) throw new ConsultingHttpError(404, "Communication was not found."); if (message.status !== "failed") throw new ConsultingHttpError(409, "Only failed communications can be recovered."); const { error: queueError } = await supabaseAdmin.from("communication_queue").upsert({ message_id: messageId, status: "retry", attempts: 0, next_attempt_at: now, last_error: null, locked_at: null }, { onConflict: "message_id" }); if (queueError) throw new Error(queueError.message); const { error: updateError } = await supabaseAdmin.from("communication_messages").update({ status: "queued", updated_at: now }).eq("id", messageId); if (updateError) throw new Error(updateError.message); await Promise.all([supabaseAdmin.from("communication_events").insert({ message_id: messageId, event_type: "queued", event_data: { recoveredBy: actorId } }), supabaseAdmin.from("communication_history").insert({ message_id: messageId, status: "manually_requeued", actor_id: actorId, details: {} })]); return { messageId, status: "queued" }; }
