import "server-only";
import { Resend } from "resend";
import { supabaseAdmin } from "@/lib/supabase/admin";

type QueueRow = { id: string; message_id: string; attempts: number };
type Recipient = { email: string; display_name: string | null };
type AttachmentRow = { storage_path: string; file_name: string; mime_type: string };

const escapeHtml = (value: string) => value.replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character] || character);
const corporateHtml = (subject: string, body: string) => `<!doctype html><html><body style="margin:0;background:#f4f7fa;font-family:Arial,sans-serif;color:#102033"><div style="display:none;max-height:0;overflow:hidden">${escapeHtml(subject)}</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td align="center" style="padding:32px 16px"><table role="presentation" width="640" style="max-width:640px;width:100%;background:#fff;border:1px solid #dbe3ea"><tr><td style="padding:28px 36px;border-bottom:3px solid #164d75"><strong style="font-size:22px">GrowXLabs<span style="color:#1479b8">.tech</span></strong></td></tr><tr><td style="padding:36px"><h1 style="font-size:24px;margin:0 0 22px">${escapeHtml(subject)}</h1><div style="font-size:16px;line-height:1.65">${body}</div></td></tr><tr><td style="padding:22px 36px;background:#f7f9fb;color:#607080;font-size:12px">GrowXLabs · Confidential client communication<br>Need help? sai@growxlabs.tech</td></tr></table></td></tr></table></body></html>`;

async function loadAttachments(messageId: string) {
  const { data } = await supabaseAdmin.from("communication_attachments").select("storage_path,file_name,mime_type").eq("message_id", messageId);
  const attachments: { filename: string; content: Buffer; contentType: string }[] = [];
  for (const row of (data || []) as AttachmentRow[]) { const slash = row.storage_path.indexOf("/"); if (slash < 1) continue; const bucket = row.storage_path.slice(0, slash); const path = row.storage_path.slice(slash + 1); const { data: file } = await supabaseAdmin.storage.from(bucket).download(path); if (file) attachments.push({ filename: row.file_name, content: Buffer.from(await file.arrayBuffer()), contentType: row.mime_type }); }
  return attachments;
}

export async function processCommunicationQueue(limit = 20) {
  if (!process.env.RESEND_API_KEY) throw new Error("RESEND_API_KEY is not configured.");
  const resend = new Resend(process.env.RESEND_API_KEY); const now = new Date().toISOString();
  const { data: rows, error } = await supabaseAdmin.from("communication_queue").select("id,message_id,attempts").in("status", ["pending", "retry", "scheduled"]).lte("next_attempt_at", now).order("next_attempt_at", { ascending: true }).limit(limit); if (error) throw new Error(error.message);
  const result = { processed: 0, sent: 0, failed: 0 };
  for (const row of (rows || []) as QueueRow[]) { result.processed += 1; const { data: claimed } = await supabaseAdmin.from("communication_queue").update({ status: "sending", locked_at: now, attempts: row.attempts + 1 }).eq("id", row.id).in("status", ["pending", "retry", "scheduled"]).select("id").maybeSingle(); if (!claimed) continue;
    try { const [{ data: message }, { data: recipients }] = await Promise.all([supabaseAdmin.from("communication_messages").select("*").eq("id", row.message_id).single(), supabaseAdmin.from("communication_recipients").select("email,display_name").eq("message_id", row.message_id)]); if (!message) throw new Error("Queued message not found."); const to = ((recipients || []) as Recipient[]).map((recipient) => recipient.email).filter(Boolean); if (!to.length) throw new Error("Message has no recipients."); if (message.status === "draft") throw new Error("Draft messages cannot be sent."); const sent = await resend.emails.send({ from: process.env.RESEND_FROM_EMAIL || "GrowXLabs <noreply@growxlabs.tech>", replyTo: process.env.RESEND_REPLY_TO || "sai@growxlabs.tech", to, subject: message.subject || "GrowXLabs update", html: corporateHtml(message.subject || "GrowXLabs update", message.body), attachments: await loadAttachments(message.id) }); if (sent.error) throw new Error(sent.error.message); await Promise.all([supabaseAdmin.from("communication_queue").update({ status: "sent", last_error: null }).eq("id", row.id), supabaseAdmin.from("communication_messages").update({ status: "sent", sent_at: now, updated_at: now }).eq("id", message.id), supabaseAdmin.from("communication_events").insert({ message_id: message.id, event_type: "sent", event_data: { provider: "resend", providerId: sent.data?.id } }), supabaseAdmin.from("communication_history").insert({ message_id: message.id, status: "sent", details: { provider: "resend" } })]); result.sent += 1;
    } catch (caught) { const attempts = row.attempts + 1; const retry = attempts < 5; const nextAttempt = new Date(Date.now() + Math.min(60, 2 ** attempts) * 60_000).toISOString(); const message = caught instanceof Error ? caught.message : "Communication delivery failed."; await Promise.all([supabaseAdmin.from("communication_queue").update({ status: retry ? "retry" : "failed", next_attempt_at: nextAttempt, last_error: message }).eq("id", row.id), supabaseAdmin.from("communication_messages").update({ status: retry ? "retry" : "failed", updated_at: now }).eq("id", row.message_id), supabaseAdmin.from("communication_events").insert({ message_id: row.message_id, event_type: "failed", event_data: { error: message, retry } })]); result.failed += 1; }
  }
  return result;
}

export function createIcs(input: { uid: string; title: string; description?: string; startsAt: Date; endsAt: Date; location?: string; organizerEmail: string }) { const stamp = (date: Date) => date.toISOString().replace(/[-:]/g, "").replace(/\.\d{3}Z$/, "Z"); const safe = (value: string) => value.replace(/([,;\\])/g, "\\$1").replace(/\n/g, "\\n"); return ["BEGIN:VCALENDAR", "VERSION:2.0", "PRODID:-//GrowXLabs//Communication Platform//EN", "METHOD:REQUEST", "BEGIN:VEVENT", `UID:${safe(input.uid)}`, `DTSTAMP:${stamp(new Date())}`, `DTSTART:${stamp(input.startsAt)}`, `DTEND:${stamp(input.endsAt)}`, `SUMMARY:${safe(input.title)}`, `DESCRIPTION:${safe(input.description || "")}`, `LOCATION:${safe(input.location || "")}`, `ORGANIZER:mailto:${input.organizerEmail}`, "STATUS:CONFIRMED", "END:VEVENT", "END:VCALENDAR"].join("\r\n"); }
