import "server-only";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/auth";
import { supabaseAdmin } from "@/lib/supabase/admin";
import { ConsultingHttpError } from "@/lib/consulting/workflow";
export { supabaseAdmin };
const admins = ["ADMIN", "CO_ADMIN"];
export async function requireSuccessAdmin() { const s = await getServerSession(authOptions); if (!s?.user?.id) throw new ConsultingHttpError(401, "Authentication required."); if (!admins.includes(s.user.role)) throw new ConsultingHttpError(403, "Client success permission is required."); return { userId: s.user.id }; }
export async function requireSuccessClient() { const s = await getServerSession(authOptions); if (!s?.user?.id || s.user.role !== "CLIENT") throw new ConsultingHttpError(403, "A client account is required."); const { data } = await supabaseAdmin.from("client_profiles").select("id").eq("user_id", s.user.id).maybeSingle(); if (!data) throw new ConsultingHttpError(403, "Client account is not linked."); return { userId: s.user.id, clientId: data.id }; }
export function successError(error: unknown) { return Response.json({ error: error instanceof Error ? error.message : "Client success request failed." }, { status: error instanceof ConsultingHttpError ? error.status : 500 }); }
async function activity(projectId: string, type: string, id: string | null, actorId: string, event: string, metadata: Record<string, unknown> = {}) { const { error } = await supabaseAdmin.from("success_activity").insert({ project_id: projectId, entity_type: type, entity_id: id, actor_id: actorId, event_type: event, metadata }); if (error) throw new Error(error.message); }
export async function createClosure(projectId: string, userId: string) {
  const { data: workspace } = await supabaseAdmin.from("project_workspaces").select("*").eq("id", projectId).maybeSingle(); if (!workspace) throw new ConsultingHttpError(404, "Project workspace not found.");
  const { data: milestones } = await supabaseAdmin.from("project_milestones").select("status").eq("project_id", projectId); const { data: tasks } = await supabaseAdmin.from("project_tasks").select("status").eq("project_id", projectId); const { data: approvals } = await supabaseAdmin.from("project_approvals").select("status").eq("project_id", projectId); const { data: tickets } = await supabaseAdmin.from("support_tickets").select("status").eq("project_id", projectId).not("status", "in", "(closed,cancelled)");
  const blockers: string[] = []; if ((milestones || []).some((m: { status: string }) => !["completed", "cancelled"].includes(m.status))) blockers.push("milestones"); if ((tasks || []).some((t: { status: string }) => !["completed", "cancelled"].includes(t.status))) blockers.push("tasks"); if ((approvals || []).some((a: { status: string }) => a.status !== "approved")) blockers.push("approvals"); if ((tickets || []).length) blockers.push("support tickets");
  const { data: existing } = await supabaseAdmin.from("project_closures").select("*").eq("project_id", projectId).maybeSingle(); if (existing) return existing;
  const { data, error } = await supabaseAdmin.from("project_closures").insert({ project_id: projectId, client_id: workspace.client_id, agreement_id: workspace.agreement_id, status: blockers.length ? "pending" : "awaiting_client_acceptance", checklist: { blockers, milestones: !blockers.includes("milestones"), tasks: !blockers.includes("tasks"), approvals: !blockers.includes("approvals"), support: !blockers.includes("support tickets") }, created_by: userId }).select("*").single(); if (error) throw new Error(error.message); await activity(projectId, "closure", data.id, userId, "closure_created", { closureNumber: data.closure_number, blockers }); return data;
}
export async function acceptClosure(closureId: string, userId: string, clientId: string) { const { data: closure } = await supabaseAdmin.from("project_closures").select("*").eq("id", closureId).eq("client_id", clientId).maybeSingle(); if (!closure) throw new ConsultingHttpError(404, "Closure record not found."); if (closure.status !== "awaiting_client_acceptance") throw new ConsultingHttpError(409, "Closure is not ready for client acceptance."); const { data, error } = await supabaseAdmin.from("project_closures").update({ status: "accepted", accepted_at: new Date().toISOString(), accepted_by: userId, updated_at: new Date().toISOString() }).eq("id", closureId).select("*").single(); if (error) throw new Error(error.message); await supabaseAdmin.from("project_workspaces").update({ status: "completed", updated_at: new Date().toISOString() }).eq("id", closure.project_id); await activity(closure.project_id, "closure", closure.id, userId, "closure_accepted", { closureNumber: closure.closure_number }); return data; }
export async function createSuccessReview(projectId: string, userId: string, input: Record<string, unknown> = {}) { const { data: workspace } = await supabaseAdmin.from("project_workspaces").select("client_id,status").eq("id", projectId).maybeSingle(); if (!workspace || workspace.status !== "completed") throw new ConsultingHttpError(409, "Customer success starts after project closure."); const { data: existing } = await supabaseAdmin.from("customer_success_reviews").select("*").eq("project_id", projectId).maybeSingle(); if (existing) return existing; const { data, error } = await supabaseAdmin.from("customer_success_reviews").insert({ project_id: projectId, client_id: workspace.client_id, health: input.health || "healthy", reasons: input.reasons || [], recommendations: [{ content: "Draft — Requires Human Review" }], created_by: userId }).select("*").single(); if (error) throw new Error(error.message); await activity(projectId, "success_review", data.id, userId, "success_review_created", { reviewNumber: data.review_number }); return data; }
export async function createQbr(projectId: string, userId: string, input: Record<string, unknown>) { const { data: workspace } = await supabaseAdmin.from("project_workspaces").select("client_id,status").eq("id", projectId).maybeSingle(); if (!workspace || workspace.status !== "completed") throw new ConsultingHttpError(409, "Quarterly reviews require a closed project."); const { data, error } = await supabaseAdmin.from("quarterly_business_reviews").insert({ project_id: projectId, client_id: workspace.client_id, review_period: input.reviewPeriod || null, goals: input.goals || [], kpis: input.kpis || [], recommendations: [{ content: "Draft — Requires Human Review" }], created_by: userId }).select("*").single(); if (error) throw new Error(error.message); await activity(projectId, "qbr", data.id, userId, "qbr_created", { qbrNumber: data.qbr_number }); return data; }
export async function createExpansion(projectId: string, userId: string, input: Record<string, unknown>) { if (!input.title || !input.category) throw new ConsultingHttpError(400, "Opportunity title and category are required."); const { data: workspace } = await supabaseAdmin.from("project_workspaces").select("client_id").eq("id", projectId).maybeSingle(); if (!workspace) throw new ConsultingHttpError(404, "Project not found."); const { data, error } = await supabaseAdmin.from("expansion_opportunities").insert({ project_id: projectId, client_id: workspace.client_id, title: input.title, category: input.category, business_value: input.businessValue || null, estimated_effort: input.estimatedEffort || null, priority: input.priority || "medium", recommendation: "Draft — Requires Human Review", created_by: userId }).select("*").single(); if (error) throw new Error(error.message); await activity(projectId, "expansion", data.id, userId, "expansion_identified", { expansionNumber: data.expansion_number }); return data; }
